import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const root=path.resolve('.sites-runtime/reader-ai-tests');fs.mkdirSync(root,{recursive:true});
for(const [name,file] of [['remote','lib/remote.ts'],['ai-text','lib/ai-text.ts'],['route','app/api/ai/route.ts']]){const source=fs.readFileSync(file,'utf8').replaceAll("@/lib/remote","./remote.mjs").replaceAll("@/lib/ai-text","./ai-text.mjs");fs.writeFileSync(`${root}/${name}.mjs`,ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);}
const {POST}=await import(`${root}/route.mjs`);const {translationChunks}=await import(`${root}/ai-text.mjs`);
const input={base:'https://provider.example/v1/chat/completions/ ',key:' test-key ',model:' test-model ',task:'translate',content:'Hello world',target:'简体中文'};
function request(extra={}){return new Request('https://reader.example/api/ai',{method:'POST',body:JSON.stringify({...input,...extra})});}
function mock(t,callback){const original=globalThis.fetch;globalThis.fetch=callback;t.after(()=>{globalThis.fetch=original;});}
test('translation calls normalized API with target and returns actual text',async t=>{mock(t,async(url,options)=>{assert.equal(String(url),'https://provider.example/v1/chat/completions');assert.equal(options.headers.Authorization,'Bearer test-key');const data=JSON.parse(options.body);assert.equal(data.model,'test-model');assert.match(data.messages[0].content,/简体中文/);assert.match(data.messages[1].content,/Hello world/);return Response.json({choices:[{message:{content:'你好，世界'},finish_reason:'stop'}]});});const response=await POST(request());assert.equal(response.status,200);assert.equal((await response.json()).answer,'你好，世界');});
test('structured text blocks are accepted without exposing reasoning content',async t=>{mock(t,async()=>Response.json({choices:[{message:{content:[{type:'reasoning',text:'private thoughts'},{type:'text',text:'译文'}]}}]}));assert.deepEqual(await (await POST(request())).json(),{answer:'译文'});});
test('non-JSON upstream errors remain actionable',async t=>{mock(t,async()=>new Response('<html>gateway error</html>',{status:502}));const r=await POST(request());assert.equal(r.status,400);assert.match((await r.json()).error,/502.*API 地址/);});
test('upstream quota errors and truncation never report successful translation',async t=>{mock(t,async()=>Response.json({error:{message:'Insufficient credits'}},{status:402}));assert.match((await (await POST(request())).json()).error,/402.*Insufficient credits/);globalThis.fetch=async()=>Response.json({choices:[{message:{content:'partial'},finish_reason:'length'}]});assert.match((await (await POST(request())).json()).error,/长度限制/);});
test('quoted question sends exact selection and nearby context',async t=>{mock(t,async(url,options)=>{const content=JSON.parse(options.body).messages[1].content;assert.match(content,/<quoted_text>\nturn out\n<\/quoted_text>/);assert.match(content,/It will turn out well/);assert.match(content,/用户问题：是什么意思/);return Response.json({choices:[{message:{content:'这里表示结果是。'}}]});});const response=await POST(request({task:'ask',quote:'turn out',question:'是什么意思',content:'It will turn out well'}));assert.equal(response.status,200);});
test('translation chunking preserves every character including emoji and paragraph boundaries',()=>{const text='开头\n\n'+'a'.repeat(2994)+'😀'+'more text\n'.repeat(800);const chunks=translationChunks(text);assert.ok(chunks.length>2);assert.equal(chunks.join(''),text);assert.ok(chunks.every(c=>c.length<=3000));assert.ok(chunks.every(c=>!/[\uD800-\uDBFF]$/.test(c)));});
