import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import {JSDOM} from 'jsdom';
const dir=path.resolve('.sites-runtime/workspace-tests');fs.mkdirSync(dir,{recursive:true});
for(const [name,file] of [['ink','lib/ink.ts'],['feed','lib/feed-reader.ts'],['remote','lib/remote.ts'],['journal-feed','lib/journal-feed.ts'],['bili','lib/bili-client.ts']])fs.writeFileSync(`${dir}/${name}.mjs`,ts.transpileModule(fs.readFileSync(file,'utf8').replace("from './remote'","from './remote.mjs'").replace("from './journal-feed'","from './journal-feed.mjs'"),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const {hitStroke,insidePolygon,moveStrokes}=await import(dir+'/ink.mjs'),{parseFeed,parseOPML,exportOPML,feedRequest}=await import(dir+'/feed.mjs'),{documentText}=await import(dir+'/remote.mjs'),{wbiQuery,biliRequest,biliJsonFeed,clearBiliSession}=await import(dir+'/bili.mjs');
const dom=new JSDOM();globalThis.DOMParser=dom.window.DOMParser;
test('eraser hits a segment between samples and lasso moves the selection without losing shape',()=>{const a={color:'#173b32',width:2,points:[[20,20],[80,20]]},b={...a,points:[[200,200],[230,250]]};assert.ok(hitStroke(a,[50,22]));assert.ok(!hitStroke(a,[50,100]));assert.ok(insidePolygon([50,20],[[10,10],[100,10],[100,30],[10,30]]));const moved=moveStrokes([a,b],[0],-100,40);assert.deepEqual(moved[0].points,[[0,60],[60,60]]);assert.deepEqual(moved[1],b);});
test('OPML preserves escaped titles and folders, filters executable URLs and deduplicates',()=>{const feeds=[{id:'1',name:'A & B',url:'https://example.com/rss?a=1&b=2',category:'AI / 科技'}];assert.deepEqual(parseOPML(exportOPML(feeds)).map(x=>[x.name,x.url,x.category]),[['A & B',feeds[0].url,'AI / 科技']]);assert.equal(parseOPML('<opml><body><outline xmlUrl="javascript:alert(1)"/><outline xmlUrl="https://a.example/rss"/><outline xmlUrl="https://a.example/rss"/></body></opml>').length,1);});
test('RSS audio enclosures render as audio and ordinary articles do not get a false media URL',()=>{const xml='<rss><channel><title>Podcast</title><item><guid>a</guid><title>Episode</title><link>https://example.com/a</link><description>Intro</description><enclosure url="https://example.com/a.mp3" type="audio/mpeg"/></item><item><guid>b</guid><title>Text</title><link>https://example.com/b</link><description>Words</description></item></channel></rss>';const {items}=parseFeed(xml,'https://example.com/feed');assert.equal(items[0].type,'audio');assert.equal(items[0].media,'https://example.com/a.mp3');assert.equal(items[1].type,'article');assert.equal(items[1].media,undefined);assert.equal(items[1].cover,undefined);});
test('Bilibili投稿成为带稳定视频ID的JSON Feed and escapes descriptions',()=>{const feed=biliJsonFeed({list:{vlist:[{bvid:'BV123abc',title:'Title',author:'Creator',description:'<script>bad</script>',created:1700000000}]}},'123','video','https://reader.example/api/bilibili?mode=feed');const parsed=parseFeed(JSON.stringify(feed),'https://reader.example/api/bilibili?mode=feed');assert.equal(parsed.items[0].bvid,'BV123abc');assert.equal(parsed.items[0].type,'video');assert.ok(!feed.items[0].content_html.includes('<script>'));assert.throws(()=>biliJsonFeed({},'123','video','https://example.com'));});
test('article decoder respects declared Chinese charset',async()=>{const r=new Response(new Uint8Array([0xd6,0xd0,0xce,0xc4]),{headers:{'content-type':'text/html; charset=gbk'}});assert.equal(await documentText(r),'中文');});
test('WBI canonical query sorts, filters reserved characters and uses public-key hash',()=>{const q=wbiQuery({z:"a b!()'",a:'中文'},'a'.repeat(32),'b'.repeat(32),1700000000);const text='a=%E4%B8%AD%E6%96%87&wts=1700000000&z=a%20b';assert.ok(q.startsWith(text+'&w_rid='));assert.match(q,/w_rid=[a-f0-9]{32}$/);assert.equal(new URLSearchParams(q).get('z'),'a b');assert.notEqual(q,wbiQuery({z:'a b',a:'中文'},'a'.repeat(32),'b'.repeat(32),1700000001));});
test('Bili client refreshes stale signing keys once but does not retry a risk challenge',async t=>{clearBiliSession();const original=globalThis.fetch;t.after(()=>{globalThis.fetch=original;clearBiliSession();});let nav=0,queries=0;globalThis.fetch=async url=>{const p=new URL(url).pathname;if(p.endsWith('/spi'))return Response.json({code:0,data:{b_3:'visitor'}});if(p.endsWith('/nav')){nav++;return Response.json({code:-101,data:{wbi_img:{img_url:'https://i.example/'+ 'a'.repeat(32)+'.png',sub_url:'https://i.example/'+'b'.repeat(32)+'.png'}}});}queries++;return Response.json(queries===1?{code:-403}:{code:0,data:{ok:true}});};assert.deepEqual(await biliRequest('/x/web-interface/wbi/search/type',{keyword:'test'},true,AbortSignal.timeout(1000)),{ok:true});assert.equal(nav,2);assert.equal(queries,2);globalThis.fetch=async()=>{queries++;return Response.json({code:-352,message:'challenge'});};await assert.rejects(()=>biliRequest('/x/web-interface/wbi/search/type',{},true,AbortSignal.timeout(1000)),/352/);assert.equal(queries,3);});

test('explicit RSSHub fallback stays with the selected RSSHub instance',()=>{const rss='https://hub.example.com/bilibili/user/video/123';assert.deepEqual(feedRequest(rss,'https://reader.example'),{direct:false,url:'/api/feed?url='+encodeURIComponent(rss)});assert.deepEqual(feedRequest('https://reader.example/api/bilibili?mode=feed&uid=123','https://reader.example'),{direct:true,url:'/api/bilibili?mode=feed&uid=123'});});
test('public rankings do not depend on visitor or signing endpoints',async t=>{clearBiliSession();const original=globalThis.fetch;t.after(()=>{globalThis.fetch=original;clearBiliSession();});let count=0;globalThis.fetch=async url=>{count++;assert.equal(new URL(url).pathname,'/x/web-interface/ranking/v2');return Response.json({code:0,data:{list:[]}});};assert.deepEqual(await biliRequest('/x/web-interface/ranking/v2',{rid:'0',type:'all'},false,AbortSignal.timeout(1000)),{list:[]});assert.equal(count,1);});
test('cancelling one visitor initialization does not cancel a concurrent reader',async t=>{clearBiliSession();const original=globalThis.fetch;t.after(()=>{globalThis.fetch=original;clearBiliSession();});let first=true;globalThis.fetch=async(url,options)=>{const path=new URL(url).pathname;if(path.endsWith('/spi')){if(first){first=false;return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(options.signal.reason),{once:true}));}return Response.json({code:0,data:{b_3:'second-reader'}});}if(path.endsWith('/nav'))return Response.json({code:-101,data:{wbi_img:{img_url:'https://i.example/'+ 'a'.repeat(32)+'.png',sub_url:'https://i.example/'+'b'.repeat(32)+'.png'}}});return Response.json({code:0,data:{ok:true}});};const aborted=new AbortController();const a=biliRequest('/x/web-interface/wbi/search/type',{},true,aborted.signal);const rejects=assert.rejects(a);const b=biliRequest('/x/web-interface/wbi/search/type',{},true,AbortSignal.timeout(1000));aborted.abort();await rejects;assert.deepEqual(await b,{ok:true});});
