import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import {JSDOM} from 'jsdom';
const dir=path.resolve('.sites-runtime/notes-tests');fs.mkdirSync(dir,{recursive:true});
fs.writeFileSync(dir+'/anchor.mjs',ts.transpileModule(fs.readFileSync('lib/note-anchor.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
fs.writeFileSync(dir+'/session.mjs',ts.transpileModule(fs.readFileSync('lib/notebook-session.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
fs.writeFileSync(dir+'/board.mjs',ts.transpileModule(fs.readFileSync('lib/board.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const {captureAnchor,locateAnchor,anchorRange}=await import(dir+'/anchor.mjs');
test('anchors distinguish repeated words and relocate after a paragraph is inserted',()=>{const a={quote:'谷歌',start:8,end:10,prefix:'第一段谷歌。第二段',suffix:'发布新品'};const text='第一段谷歌。第二段谷歌发布新品';a.start=text.lastIndexOf('谷歌');a.end=a.start+2;assert.deepEqual(locateAnchor(text,a),[a.start,a.end]);assert.deepEqual(locateAnchor('新增段落。'+text,a),[a.start+5,a.end+5]);assert.equal(locateAnchor('无匹配内容',a),null);});
test('selection across inline elements captures and restores exact range without changing DOM',()=>{const dom=new JSDOM('<div id="body">关于<b>谷歌</b>的介绍与谷歌新闻</div>');globalThis.document=dom.window.document;globalThis.NodeFilter=dom.window.NodeFilter;const root=document.querySelector('#body'),range=document.createRange();range.setStart(root.firstChild,1);range.setEnd(root.querySelector('b').firstChild,2);const a=captureAnchor(root,range);assert.equal(a.quote,'于谷歌');assert.equal(anchorRange(root,a).toString(),a.quote);assert.equal(root.querySelectorAll('b').length,1);});
const rows=new Map(),objects=new Map();globalThis.__notesEnv={DB:{prepare(sql){return {bind(...args){return {async first(){if(sql==='SELECT owner FROM notes WHERE id=?')return rows.get(args[0])||null;if(sql.includes('WHERE owner=? LIMIT'))return [...rows.values()].find(x=>x.owner===args[0])||null;return rows.get(args[0])?.owner===args[1]?rows.get(args[0]):null;},async all(){return {results:[...rows.values()].filter(r=>r.owner===args[0]&&(!sql.includes('AND article=?')||r.article===args[1]))};},async run(){if(sql.startsWith('INSERT')){const [id,owner,article,data,audio,updated]=args;if(!rows.has(id)||rows.get(id).owner===owner)rows.set(id,{id,owner,article,data,audio,updated});}else if(rows.get(args[0])?.owner===args[1])rows.delete(args[0]);}};}};}},BUCKET:{async put(key,body,metadata){objects.set(key,{body,httpMetadata:metadata.httpMetadata});},async get(key){return objects.get(key);},async delete(key){objects.delete(key);}}};
fs.writeFileSync(dir+'/route.mjs',ts.transpileModule(fs.readFileSync('app/api/notes/route.ts','utf8').replace("import {env} from 'cloudflare:workers';","const env=globalThis.__notesEnv;").replace('@/lib/notebook-session','./session.mjs').replace('@/lib/board','./board.mjs'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const {GET,POST,DELETE}=await import(dir+'/route.mjs');
test('saved notes survive requests and remain private across browser credentials',async()=>{const initial=await GET(new Request('https://reader.test/api/notes?article=a'));const cookie=initial.headers.get('set-cookie').split(';')[0];const note={id:crypto.randomUUID(),article:'a',view:'original',kind:'text',text:'解释',quote:'谷歌',start:0,end:2,prefix:'',suffix:'',strokes:[]};const form=new FormData();form.set('note',JSON.stringify(note));assert.equal((await POST(new Request('https://reader.test/api/notes',{method:'POST',headers:{origin:'https://reader.test',cookie},body:form}))).status,200);assert.equal((await (await GET(new Request('https://reader.test/api/notes?article=a',{headers:{cookie}}))).json()).notes[0].text,'解释');assert.equal((await (await GET(new Request('https://reader.test/api/notes?article=a'))).json()).notes.length,0);await DELETE(new Request('https://reader.test/api/notes?id='+note.id,{method:'DELETE',headers:{origin:'https://reader.test'}}));assert.equal(rows.size,1);const bad=await POST(new Request('https://reader.test/api/notes',{method:'POST',headers:{origin:'https://evil.test',cookie},body:form}));assert.equal(bad.status,400);});
test('recording upload, playback ownership and removal are enforced',async()=>{const initial=await GET(new Request('https://reader.test/api/notes?article=audio'));const cookie=initial.headers.get('set-cookie').split(';')[0];const id=crypto.randomUUID(),note={id,article:'audio',view:'original',kind:'audio',text:'',quote:'',start:0,end:0,prefix:'',suffix:'',strokes:[]};const form=new FormData();form.set('note',JSON.stringify(note));form.set('audio',new Blob(['sample-audio'],{type:'audio/mp4'}),'clip.mp4');assert.equal((await POST(new Request('https://reader.test/api/notes',{method:'POST',headers:{origin:'https://reader.test',cookie},body:form}))).status,200);assert.equal(objects.size,1);assert.equal((await GET(new Request('https://reader.test/api/notes?audio='+id))).status,404);const playback=await GET(new Request('https://reader.test/api/notes?audio='+id,{headers:{cookie}}));assert.equal(playback.headers.get('content-type'),'audio/mp4');assert.equal(await playback.text(),'sample-audio');await DELETE(new Request('https://reader.test/api/notes?id='+id,{method:'DELETE',headers:{origin:'https://reader.test',cookie}}));assert.equal(objects.size,0);});

fs.writeFileSync(dir+'/notebook.mjs',ts.transpileModule(fs.readFileSync('app/api/notebook/route.ts','utf8').replace("import {env} from 'cloudflare:workers';","const env=globalThis.__notesEnv;").replace('@/lib/notebook-session','./session.mjs').replace('@/lib/board','./board.mjs'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const notebook=await import(dir+'/notebook.mjs');
test('restoring a notebook reopens the same saved notes without sharing another visitor data',async()=>{const cookie='reader_notebook='+'a'.repeat(64);const f=new FormData();f.set('note',JSON.stringify({id:crypto.randomUUID(),article:'restore',view:'original',kind:'text',text:'persistent',quote:'',start:0,end:0,prefix:'',suffix:'',strokes:[]}));assert.equal((await POST(new Request('https://reader.test/api/notes',{method:'POST',headers:{origin:'https://reader.test',cookie},body:f}))).status,200);const r=await notebook.POST(new Request('https://reader.test/api/notebook',{method:'POST',headers:{origin:'https://reader.test'},body:JSON.stringify({code:'a'.repeat(64)})}));assert.equal(r.status,200);const restored=r.headers.get('set-cookie').split(';')[0];assert.equal((await (await GET(new Request('https://reader.test/api/notes?article=restore',{headers:{cookie:restored}}))).json()).notes[0].text,'persistent');});
test('ambiguous anchors do not attach a note to the wrong repeated word',()=>{assert.equal(locateAnchor('谷歌与谷歌',{quote:'谷歌',start:99,end:101,prefix:'changed',suffix:'changed'}),null);});

test('free boards persist nodes and edges and remain private in the all-notes reference index',async()=>{const {makeBoard}=await import(dir+'/board.mjs');const board=makeBoard('large','研究');board.nodes=[{id:'a',x:20,y:20,w:200,h:100,text:'起点'},{id:'b',x:400,y:20,w:200,h:100,text:'终点'}];board.edges=[{id:'edge',from:'a',to:'b',label:'引用'}];const initial=await GET(new Request('https://reader.test/api/notes?article=%40boards'));const cookie=initial.headers.get('set-cookie').split(';')[0],form=new FormData();form.set('note',JSON.stringify(board));assert.equal((await POST(new Request('https://reader.test/api/notes',{method:'POST',headers:{origin:'https://reader.test',cookie},body:form}))).status,200);const own=(await (await GET(new Request('https://reader.test/api/notes?all=1',{headers:{cookie}}))).json()).notes;assert.equal(own.find(n=>n.id===board.id).edges[0].to,'b');assert.equal((await (await GET(new Request('https://reader.test/api/notes?all=1'))).json()).notes.length,0);const attempt=await POST(new Request('https://reader.test/api/notes',{method:'POST',headers:{origin:'https://reader.test'},body:form}));assert.equal(attempt.status,400);});
