import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';
const root=path.resolve('.sites-runtime/integration-tests');fs.mkdirSync(root,{recursive:true});
for(const [name,file] of [['remote','lib/remote.ts'],['bili-client','lib/bili-client.ts'],['translation','lib/translation.ts'],['translate-route','app/api/translate/route.ts'],['bilibili','lib/bilibili.ts'],['bili-route','app/api/bilibili/route.ts'],['catalog','lib/feed-catalog.ts']]){const source=fs.readFileSync(file,'utf8').replaceAll('@/lib/remote','./remote.mjs').replaceAll('@/lib/translation','./translation.mjs').replaceAll('@/lib/bilibili','./bilibili.mjs').replaceAll('@/lib/bili-client','./bili-client.mjs').replaceAll("from './remote'","from './remote.mjs'");fs.writeFileSync(`${root}/${name}.mjs`,ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);}
const {POST}=await import(`${root}/translate-route.mjs`);const {GET}=await import(`${root}/bili-route.mjs`);const {biliUid,biliCreators}=await import(`${root}/bilibili.mjs`);const {feedCatalog,searchCatalog}=await import(`${root}/catalog.mjs`);
function request(extra={}){return new Request('https://reader.example/api/translate',{method:'POST',body:JSON.stringify({provider:'google',key:'test',text:'A & B',target:'简体中文',...extra})});}
function mock(t,fn){const orig=globalThis.fetch;globalThis.fetch=fn;t.after(()=>{globalThis.fetch=orig;});}
test('Google translates independently of AI and decodes escaped output',async t=>{mock(t,async(url,options)=>{assert.equal(new URL(url).hostname,'translation.googleapis.com');assert.equal(new URL(url).searchParams.get('key'),'test');assert.deepEqual(JSON.parse(options.body),{q:'A & B',target:'zh-CN',format:'text',model:'nmt'});return Response.json({data:{translations:[{translatedText:'甲 &amp; 乙 &#39;引文&#39;'}]}});});const r=await POST(request());assert.equal(r.status,200);assert.equal((await r.json()).answer,"甲 & 乙 '引文'");});
test('DeepL uses correct plan, auth, language and context for natural text',async t=>{mock(t,async(url,options)=>{assert.equal(new URL(url).hostname,'api-free.deepl.com');assert.equal(options.headers.Authorization,'DeepL-Auth-Key test');const body=JSON.parse(options.body);assert.equal(body.target_lang,'ZH-HANT');assert.equal(body.context,'Nearby paragraph');assert.equal(body.model_type,'prefer_quality_optimized');assert.match(body.custom_instructions[0],/natural/);return Response.json({translations:[{text:'甲與乙'}]});});assert.equal((await (await POST(request({provider:'deepl',target:'繁體中文',context:'Nearby paragraph',style:'natural'}))).json()).answer,'甲與乙');});
test('translation quotas and missing credentials are explicit failures',async t=>{mock(t,async()=>new Response('{}',{status:456}));assert.match((await (await POST(request({provider:'deepl'}))).json()).error,/额度/);assert.match((await (await POST(request({key:''}))).json()).error,/密钥/);});
test('Bilibili UID resolution rejects spoofed domains and accepts profile links',()=>{assert.equal(biliUid('https://space.bilibili.com/946974/upload/video'),'946974');assert.equal(biliUid('517327498'),'517327498');assert.equal(biliUid('https://space.bilibili.com.evil.example/946974'),'');});
test('Bilibili ranking authors are deduplicated without inventing rank or fan counts',()=>{const rows=biliCreators({list:[{owner:{mid:1,name:'One'},title:'V1',bvid:'BV1xx'},{owner:{mid:1,name:'One'},title:'V2'},{owner:{mid:2,name:'Two'},title:'V3'}]},'ranking');assert.equal(rows.length,2);assert.equal(rows[1].rank,3);assert.equal(rows[0].fans,undefined);});
test('Bilibili signed search and rejection stay distinct',async t=>{mock(t,async(url)=>{const u=new URL(url);if(u.pathname.endsWith('/spi'))return Response.json({code:0,data:{b_3:'test-visitor',b_4:'test-visitor4'}});if(u.pathname.endsWith('/nav'))return Response.json({code:-101,data:{wbi_img:{img_url:'https://example.com/'+ 'a'.repeat(32)+'.png',sub_url:'https://example.com/'+'b'.repeat(32)+'.png'}}});assert.equal(u.pathname,'/x/web-interface/wbi/search/type');assert.ok(u.searchParams.get('w_rid'));assert.equal(u.searchParams.get('search_type'),'bili_user');return Response.json({code:0,data:{result:[{mid:946974,uname:'<em>影视</em>飓风',fans:100}]}});});const r=await GET(new Request('https://reader.example/api/bilibili?mode=search&q=影视'));assert.equal((await r.json()).creators[0].name,'影视飓风');globalThis.fetch=async()=>Response.json({code:-352,message:'风控校验失败'});const blocked=await GET(new Request('https://reader.example/api/bilibili?mode=popular'));assert.equal(blocked.status,502);assert.match((await blocked.json()).error,/-352/);});
test('feed directory has unique HTTPS sources and category/language search',()=>{assert.ok(feedCatalog.length>=40);assert.equal(new Set(feedCatalog.map(x=>x.url)).size,feedCatalog.length);assert.ok(feedCatalog.every(x=>new URL(x.url).protocol==='https:'));assert.equal(searchCatalog('少数派')[0].url,'https://sspai.com/feed');assert.ok(searchCatalog('','AI与开发','English').every(x=>x.category==='AI与开发'&&x.language==='English'));});
