'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {captureAnchor,anchorRange,type Anchor} from '@/lib/note-anchor';
type Stroke={color:string;width:number;points:number[][]};
type Note=Anchor&{id:string;article:string;kind:string;text:string;strokes:Stroke[];view:string;hasAudio?:boolean;updated?:number};
function caret(x:number,y:number){const d=document as any;if(d.caretRangeFromPoint)return d.caretRangeFromPoint(x,y) as Range|null;const p=d.caretPositionFromPoint?.(x,y);if(!p)return null;const r=document.createRange();r.setStart(p.offsetNode,p.offset);r.collapse(true);return r;}
export function ArticleNotes({article,view,children}:{article:string;view:string;children:ReactNode}){
 const root=useRef<HTMLDivElement>(null),[notes,setNotes]=useState<Note[]>([]),[selection,setSelection]=useState<Anchor|null>(null),[draft,setDraft]=useState<Note|null>(null),[panel,setPanel]=useState(false),[pen,setPen]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[marks,setMarks]=useState<{id:string;x:number;y:number;w:number;h:number}[]>([]);
 const [color,setColor]=useState('#173b32'),[width,setWidth]=useState(4),[finger,setFinger]=useState(false),[recording,setRecording]=useState(false),[clip,setClip]=useState<Blob|null>(null),[clipUrl,setClipUrl]=useState('');const stroke=useRef<Stroke|null>(null),inkPointer=useRef<number|null>(null),[live,setLive]=useState<Stroke|null>(null),rec=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true),penStart=useRef<Range|null>(null);
 async function load(){setLoading(true);try{const r=await fetch('/api/notes?article='+encodeURIComponent(article));const d=await r.json();if(!r.ok)throw new Error(d.error);if(alive.current){setNotes(d.notes);setError('');}}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setLoading(false);}}
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;if(timer.current)clearTimeout(timer.current);if(rec.current?.state==='recording')rec.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[article]);
 useEffect(()=>{if(!clip){setClipUrl('');return;}const url=URL.createObjectURL(clip);setClipUrl(url);return()=>URL.revokeObjectURL(url);},[clip]);
 useEffect(()=>{function capture(){if(draft)return;const s=window.getSelection();if(!s||s.isCollapsed||!root.current||!root.current.contains(s.anchorNode)||!root.current.contains(s.focusNode))return;const a=captureAnchor(root.current,s.getRangeAt(0));if(a.quote.trim()&&a.quote.length<=10000)setSelection(a);}document.addEventListener('selectionchange',capture);return()=>document.removeEventListener('selectionchange',capture);},[draft]);
 useEffect(()=>{const el=root.current;if(!el)return;function redraw(){if(!el)return;const b=el.getBoundingClientRect();setMarks(notes.filter(n=>n.view===view).flatMap(n=>{const r=anchorRange(el,n);return r?Array.from(r.getClientRects()).filter(x=>x.width>0).map(x=>({id:n.id,x:x.left-b.left,y:x.top-b.top,w:x.width,h:x.height})):[];}));}redraw();const ro=new ResizeObserver(redraw);ro.observe(el);const mo=new MutationObserver(redraw);mo.observe(el,{childList:true,subtree:true,characterData:true});window.addEventListener('resize',redraw);return()=>{ro.disconnect();mo.disconnect();window.removeEventListener('resize',redraw);};},[notes,view,children]);
 function create(kind:string,a=selection){setClip(null);setError('');setDraft({...(a||{quote:'',start:0,end:0,prefix:'',suffix:''}),id:crypto.randomUUID(),article,view,kind,text:'',strokes:[]});setSelection(null);window.getSelection()?.removeAllRanges();}
 async function save(){if(!draft||saving||recording)return;setSaving(true);setError('');try{const f=new FormData();f.set('note',JSON.stringify(draft));if(clip)f.set('audio',clip,'recording');const r=await fetch('/api/notes',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);setDraft(null);setClip(null);setPanel(true);await load();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 async function remove(n:Note){if(!window.confirm('删除这条笔记及其录音？'))return;try{const r=await fetch('/api/notes?id='+encodeURIComponent(n.id),{method:'DELETE'});if(!r.ok)throw new Error('删除失败，请重试');setNotes(v=>v.filter(x=>x.id!==n.id));}catch(e){setError((e as Error).message);}}
 async function record(){try{setError('');setRecording(true);if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('此浏览器不支持录音，可以上传已有录音');const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;const mime=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(x=>MediaRecorder.isTypeSupported(x));const r=new MediaRecorder(s,mime?{mimeType:mime}:undefined),chunks:BlobPart[]=[];let size=0;rec.current=r;r.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>11000000&&r.state==='recording')r.stop();}};r.onstop=()=>{if(timer.current)clearTimeout(timer.current);s.getTracks().forEach(t=>t.stop());if(alive.current){setClip(new Blob(chunks,{type:r.mimeType}));setRecording(false);}};r.onerror=()=>{s.getTracks().forEach(t=>t.stop());setRecording(false);setError('录音中断，请重试或上传录音');};r.start(1000);setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},300000);}catch(e){setRecording(false);setError((e as Error).message);}}
 function point(e:React.PointerEvent<SVGSVGElement>){const b=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1000,(e.clientX-b.left)*1000/b.width)),Math.max(0,Math.min(650,(e.clientY-b.top)*650/b.height))];}
 function finish(){inkPointer.current=null;if(stroke.current){const s=stroke.current;setDraft(n=>n?{...n,strokes:[...n.strokes,s]}:n);stroke.current=null;setLive(null);}}
 return <div className={'notebook '+(panel?'notes-open':'')}><div className="notebook-bar"><span>阅读与批注</span><button aria-pressed={pen} onClick={()=>setPen(!pen)}>{pen?'✓ 笔划标记中':'笔划标记'}</button><button onClick={()=>create('text',null)}>＋整篇笔记</button><button aria-expanded={panel} onClick={()=>setPanel(!panel)}>笔记 {notes.length} {panel?'收起':'展开'}</button></div>{pen&&<p className="note-hint">用笔从词句开头划到结尾即可选中，再添加下划线或笔记；标记模式暂停正文滚动，完成后关闭即可继续阅读。</p>}<div className="annotated-content"><div ref={root} style={{touchAction:pen?'none':'auto'}} onPointerDownCapture={e=>{if(!pen||e.pointerType!=='pen')return;e.preventDefault();penStart.current=caret(e.clientX,e.clientY);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUpCapture={e=>{if(!pen||e.pointerType!=='pen'||!penStart.current||!root.current)return;const end=caret(e.clientX,e.clientY),start=penStart.current;penStart.current=null;if(!end||!root.current.contains(start.startContainer)||!root.current.contains(end.startContainer))return;try{const r=document.createRange();if(start.compareBoundaryPoints(Range.START_TO_START,end)<=0){r.setStart(start.startContainer,start.startOffset);r.setEnd(end.startContainer,end.startOffset);}else{r.setStart(end.startContainer,end.startOffset);r.setEnd(start.startContainer,start.startOffset);}const a=captureAnchor(root.current,r);if(a.quote.trim())setSelection(a);}catch{setError('请从文字开头划到结尾重试');}}}>{children}</div><div className="note-marks" aria-hidden="true">{marks.map((m,i)=><span key={i} style={{left:m.x,top:m.y,width:m.w,height:m.h}}/>)}</div></div>
 {selection&&<div className="note-selection"><span>“{selection.quote.slice(0,35)}”</span>{[['underline','下划线'],['text','文字'],['draft','手写草稿'],['audio','录音']].map(([k,l])=><button key={k} onClick={()=>create(k)}>{l}</button>)}<button aria-label="取消批注选择" onClick={()=>setSelection(null)}>×</button></div>}
 {panel&&<aside className="notes-panel"><h3>本篇笔记 <small>{notes.length}</small></h3><p className="note-hint">保存在服务端，由当前浏览器的笔记凭证访问。清除网站 Cookie 会失去访问入口；尚不支持跨设备同步。</p>{loading&&<p>读取笔记…</p>}{error&&!draft&&<p role="alert">{error}<button onClick={()=>void load()}>重试</button></p>}{!loading&&!notes.length&&<p>选中原文中的词句，留下你的想法。</p>}{notes.map(n=><section className="note-card" key={n.id}><small>{n.kind==='draft'?'手写草稿':n.kind==='audio'?'录音笔记':n.kind==='underline'?'下划线':'文字笔记'} · {n.view==='original'?'原文':'译文'}</small>{n.quote&&<button className="note-quote" onClick={()=>{const r=root.current&&anchorRange(root.current,n);if(n.view!==view||!r){setError('请切换到对应原文／译文后定位；正文变化可能使标记无法匹配。');return;}r.startContainer.parentElement?.scrollIntoView({block:'center',behavior:'smooth'});}}>{n.quote}</button>}{n.text&&<p>{n.text}</p>}{n.strokes.length>0&&<svg viewBox="0 0 1000 650" className="draft-thumbnail">{n.strokes.map((s,i)=><polyline key={i} points={s.points.map(p=>p.join(',')).join(' ')} stroke={s.color} strokeWidth={s.width} fill="none" strokeLinecap="round" strokeLinejoin="round"/>)}</svg>}{n.hasAudio&&<audio controls preload="none" src={'/api/notes?audio='+n.id}/>}<div><button onClick={()=>{setClip(null);setError('');setDraft(n);}}>编辑</button><button onClick={()=>void remove(n)}>删除</button></div></section>)}</aside>}
 <Dialog open={!!draft} onOpenChange={v=>{if(!v&&!saving&&!recording&&(!draft||window.confirm('关闭会放弃未保存的修改，继续吗？'))){setDraft(null);setClip(null);}}}><DialogContent className="app-dialog note-dialog"><DialogTitle>原文批注</DialogTitle><DialogDescription>文字、手写和录音可以保存在同一条笔记里。</DialogDescription>{draft&&<><blockquote className="quoted-text">{draft.quote||'整篇文章笔记'}</blockquote><label className="field">文字笔记<textarea rows={3} maxLength={20000} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})} placeholder="写下你的理解、疑问或灵感…"/></label><details open={draft.kind==='draft'||draft.strokes.length>0}><summary>手写草稿纸</summary><div className="ink-tools">{['#173b32','#2563eb','#dc2626'].map(c=><button key={c} aria-label={'笔色 '+c} aria-pressed={color===c} style={{color:c}} onClick={()=>setColor(c)}>●</button>)}{[2,4,7].map(w=><button key={w} aria-pressed={width===w} onClick={()=>setWidth(w)}>{w===2?'细':w===4?'中':'粗'}</button>)}<button onClick={()=>setDraft({...draft,strokes:draft.strokes.slice(0,-1)})}>撤销</button><label><input type="checkbox" checked={finger} onChange={e=>setFinger(e.target.checked)}/>手指书写</label></div><svg className="draft-paper" viewBox="0 0 1000 650" style={{touchAction:finger?'none':'pan-y'}} onPointerDown={e=>{if((e.pointerType==='touch'&&!finger)||inkPointer.current!==null)return;inkPointer.current=e.pointerId;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);stroke.current={color,width,points:[point(e)]};setLive({...stroke.current});}} onPointerMove={e=>{if(!stroke.current||inkPointer.current!==e.pointerId)return;e.preventDefault();stroke.current.points.push(point(e));setLive({...stroke.current});}} onPointerUp={e=>{if(e.pointerId===inkPointer.current)finish();}} onPointerCancel={e=>{if(e.pointerId===inkPointer.current)finish();}}>{[...draft.strokes,...(live?[live]:[])].map((s,i)=><polyline key={i} points={(s.points.length===1?[s.points[0],[s.points[0][0]+0.1,s.points[0][1]]]:s.points).map(p=>p.join(',')).join(' ')} stroke={s.color} strokeWidth={s.width} fill="none" strokeLinecap="round" strokeLinejoin="round"/>)}</svg><p className="note-hint">支持 Apple Pencil 和鼠标；默认忽略手指落笔。修改后点击保存。</p></details><div className="record-tools"><button disabled={saving} onClick={()=>recording?rec.current?.stop():void record()}>{recording?'■ 停止录音':'● 添加录音'}</button><label>上传录音<input type="file" accept="audio/*" disabled={recording} onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>12000000)setError('录音请小于 12 MB');else setClip(f);}}}/></label>{recording&&<span role="status">正在录音 · 最长 5 分钟</span>}</div>{(clipUrl||draft.hasAudio)&&<audio controls src={clipUrl||'/api/notes?audio='+draft.id}/>} {clip&&<small>保存后替换此笔记的原录音</small>}{error&&<p className="ai-error" role="alert">{error}</p>}<button className="primary full" disabled={saving||recording} onClick={()=>void save()}>{saving?'正在保存…':'保存笔记'+(draft.kind==='underline'?'与下划线':'')}</button></>}</DialogContent></Dialog></div>;
}
