'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {PenLine,Underline,Highlighter,MessageSquare,Mic,Sparkles,NotebookPen,X,Check,Loader2,Save,Link2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {captureAnchor,anchorRange,locateAnchor,type Anchor} from '@/lib/note-anchor';
import {InkPaper,InkPreview} from '@/components/ink-paper';
import {copyReference,type ReaderReference} from '@/lib/references';
import {toast} from 'sonner';
import {NoteAudio} from '@/components/note-audio';
import {notesFetch} from '@/lib/notes-client';
import type {Stroke} from '@/lib/ink';
type Note=Anchor&{id:string;article:string;kind:string;text:string;strokes:Stroke[];view:string;mark?:string;hasAudio?:boolean;updated?:number};
function caret(x:number,y:number){const d=document as any;if(d.caretRangeFromPoint)return d.caretRangeFromPoint(x,y) as Range|null;const p=d.caretPositionFromPoint?.(x,y);if(!p)return null;const r=document.createRange();r.setStart(p.offsetNode,p.offset);r.collapse(true);return r;}
const emptyAnchor={quote:'',start:0,end:0,prefix:'',suffix:''};
export function ArticleNotes({article,view,children,onAsk,onConfigure,focus}:{article:string;view:string;focus?:ReaderReference|null;children:ReactNode;onAsk:(quote:string,question:string,context:string)=>Promise<string>;onConfigure:()=>void}){
 const root=useRef<HTMLDivElement>(null),[notes,setNotes]=useState<Note[]>([]),[selection,setSelection]=useState<Anchor|null>(null),[draft,setDraft]=useState<Note|null>(null),[panel,setPanel]=useState(false),[pen,setPen]=useState(false),[mark,setMark]=useState('underline'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[tab,setTab]=useState('notes'),[dirty,setDirty]=useState(false),[notice,setNotice]=useState('');
 const [marks,setMarks]=useState<{id:string;x:number;y:number;w:number;h:number;mark:string}[]>([]),[recording,setRecording]=useState(false),[clip,setClip]=useState<Blob|null>(null),[clipUrl,setClipUrl]=useState('');
 const [question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[aiBusy,setAiBusy]=useState(false),[askQuote,setAskQuote]=useState<Anchor|null>(null);
 const [recovery,setRecovery]=useState(false),[code,setCode]=useState(''),[restoreCode,setRestoreCode]=useState(''),[accountMessage,setAccountMessage]=useState('');
 const rec=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true),penStart=useRef<Range|null>(null),penPointer=useRef<number|null>(null),draftRef=useRef(draft),requestSerial=useRef(0),side=useRef<HTMLElement>(null);draftRef.current=draft;
 const busy=saving||recording;
 async function load(){const serial=++requestSerial.current;setLoading(true);try{const r=await notesFetch('/api/notes?article='+encodeURIComponent(article));const d=await r.json();if(!r.ok)throw new Error(d.error);if(alive.current&&serial===requestSerial.current){setNotes(d.notes);setError('');}}catch(e){if(alive.current&&serial===requestSerial.current)setError((e as Error).message);}finally{if(alive.current&&serial===requestSerial.current)setLoading(false);}}
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;requestSerial.current++;if(timer.current)clearTimeout(timer.current);if(rec.current?.state==='recording')rec.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[article]);
 useEffect(()=>{function leave(e:Event){if(recording||saving||dirty&&!window.confirm('笔记有未保存的修改，离开并放弃吗？'))e.preventDefault();}window.addEventListener('reader-before-navigate',leave);return()=>window.removeEventListener('reader-before-navigate',leave);},[dirty,recording,saving]);
 useEffect(()=>{if(!dirty&&!recording)return;const prevent=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty,recording]);
 useEffect(()=>{if(!clip){setClipUrl('');return;}const url=URL.createObjectURL(clip);setClipUrl(url);return()=>URL.revokeObjectURL(url);},[clip]);
 useEffect(()=>{function capture(){if(pen||busy)return;const s=window.getSelection();if(!s||s.isCollapsed||!root.current||!root.current.contains(s.anchorNode)||!root.current.contains(s.focusNode))return;const a=captureAnchor(root.current,s.getRangeAt(0));if(a.quote.trim()&&a.quote.length<=10000)setSelection(a);}document.addEventListener('selectionchange',capture);return()=>document.removeEventListener('selectionchange',capture);},[pen,busy]);
 useEffect(()=>{const el=root.current;if(!el)return;let frame=0;function redraw(){cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(!el)return;const b=el.getBoundingClientRect();const visible=[...notes.filter(n=>n.view===view&&n.id!==draft?.id),...(draft?.view===view?[draft]:[])];setMarks(visible.flatMap(n=>{const r=anchorRange(el,n);return r?Array.from(r.getClientRects()).filter(x=>x.width>0).map(x=>({id:n.id,x:x.left-b.left,y:x.top-b.top,w:x.width,h:x.height,mark:n.mark||'underline'})):[];}));});}redraw();const ro=new ResizeObserver(redraw);ro.observe(el);const mo=new MutationObserver(redraw);mo.observe(el,{childList:true,subtree:true,characterData:true});window.addEventListener('resize',redraw);return()=>{cancelAnimationFrame(frame);ro.disconnect();mo.disconnect();window.removeEventListener('resize',redraw);};},[notes,view,children,draft]);
 useEffect(()=>{if(!focus||loading||!root.current||(focus.article||focus.id)!==article)return;const note=notes.find(n=>n.id===focus.id);if(note){setPanel(true);setDraft(note);setDirty(false);setTab(note.kind==='draft'?'draft':note.kind==='audio'?'audio':'notes');}if(note&&focus.field==='text'&&focus.quote){setTimeout(()=>{const input=side.current?.querySelector('textarea');const pos=locateAnchor(note.text,{quote:focus.quote!,start:focus.start||0,end:focus.end||0,prefix:focus.prefix||'',suffix:focus.suffix||''});if(input&&pos){input.focus();input.setSelectionRange(pos[0],pos[1]);input.scrollIntoView({block:'center'});}},150);return;}const quote=focus.quote||note?.quote;if(quote){const a=note&&quote===note.quote?note:{quote,start:focus.start||0,end:focus.end||0,prefix:focus.prefix||'',suffix:focus.suffix||''};const timer=setTimeout(()=>{if(!root.current)return;const r=anchorRange(root.current,a);if(r){const s=window.getSelection();s?.removeAllRanges();s?.addRange(r);r.startContainer.parentElement?.scrollIntoView({block:'center'});}else setNotice('保留了引用，但未能在当前正文唯一定位');},100);return()=>clearTimeout(timer);}if(focus.kind==='note'&&!note)setNotice('这条笔记不在当前笔记本中，请恢复原笔记本或导入备份');},[focus,loading,view]);
 function reveal(){setPanel(true);setTimeout(()=>{if(window.innerWidth<1000)side.current?.scrollIntoView({behavior:'smooth',block:'start'});},50);}
 function discard(){return !busy&&(!dirty||window.confirm('当前笔记有未保存修改，放弃修改吗？'));}
 function create(kind:string,a=selection){if(!discard())return;setClip(null);setError('');setNotice('');setDraft({...a||emptyAnchor,id:crypto.randomUUID(),article,view,kind,mark,text:'',strokes:[]});setDirty(true);setTab(kind==='draft'?'draft':kind==='audio'?'audio':'notes');setSelection(null);window.getSelection()?.removeAllRanges();reveal();}
 function change(p:Partial<Note>){if(saving)return;setDraft(n=>n?{...n,...p}:n);setDirty(true);setNotice('');}
 async function save(){if(!draft||busy)return;setSaving(true);setError('');const saved=draft;try{const f=new FormData();f.set('note',JSON.stringify(saved));if(clip)f.set('audio',clip,'recording');const r=await notesFetch('/api/notes',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);if(alive.current){setDirty(false);setNotice(d.local?'已保存到本机':'已保存');setDraft({...saved,hasAudio:saved.hasAudio||!!clip});setClip(null);await load();}}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 async function remove(n:Note){if(busy||!window.confirm('删除这条笔记及其录音？'))return;try{const r=await notesFetch('/api/notes?id='+encodeURIComponent(n.id),{method:'DELETE'});if(!r.ok)throw new Error('删除失败，请重试');setNotes(v=>v.filter(x=>x.id!==n.id));if(draft?.id===n.id){setDraft(null);setDirty(false);}}catch(e){setError((e as Error).message);}}
 async function record(){if(busy)return;try{setError('');setRecording(true);if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('此浏览器不支持录音，可以上传已有录音');const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;const mime=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(x=>MediaRecorder.isTypeSupported(x));const r=new MediaRecorder(s,mime?{mimeType:mime}:undefined),chunks:BlobPart[]=[];let size=0;rec.current=r;r.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>11000000&&r.state==='recording')r.stop();}};r.onstop=()=>{if(timer.current)clearTimeout(timer.current);s.getTracks().forEach(t=>t.stop());if(alive.current){setClip(new Blob(chunks,{type:r.mimeType}));setDirty(true);setRecording(false);}};r.onerror=()=>{s.getTracks().forEach(t=>t.stop());setRecording(false);setError('录音中断，请重试或上传录音');};r.start(1000);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},300000);}catch(e){setRecording(false);setError((e as Error).message);}}
 function openAI(){setAskQuote(selection);setQuestion('');setAnswer('');setError('');setSelection(null);setTab('ai');reveal();}
 async function ask(){if(aiBusy||!question.trim())return;setAiBusy(true);setError('');try{const a=askQuote||emptyAnchor;setAnswer(await onAsk(a.quote,question,a.prefix+a.quote+a.suffix));}catch(e){setError((e as Error).message);}finally{setAiBusy(false);}}
 function locate(n:Note){if(!root.current||n.view!==view){setError('请先切换到'+(n.view==='original'?'原文':'译文')+'再定位');return;}const r=anchorRange(root.current,n);if(!r){setError('正文发生变化，未能唯一匹配；笔记仍保留原始引用。');return;}const s=window.getSelection();s?.removeAllRanges();s?.addRange(r);r.startContainer.parentElement?.scrollIntoView({block:'center',behavior:'smooth'});}
 return <div className={'notebook notebook-v2 '+(panel?'notes-open':'')}><div className="annotation-toolbar"><div className="annotation-mode"><button aria-pressed={!pen} onClick={()=>setPen(false)}>阅读 / 选词</button><button aria-pressed={pen} onClick={()=>setPen(!pen)}><PenLine size={17}/>笔划选词</button></div><div className="mark-styles"><button title="下划线" aria-label="下划线" aria-pressed={mark==='underline'} onClick={()=>setMark('underline')}><Underline size={18}/></button><button title="高亮" aria-label="高亮" aria-pressed={mark==='highlight'} onClick={()=>setMark('highlight')}><Highlighter size={18}/></button><button title="波浪线" aria-label="波浪线" aria-pressed={mark==='wavy'} onClick={()=>setMark('wavy')}>﹏</button><button title="双线" aria-label="双线" aria-pressed={mark==='double'} onClick={()=>setMark('double')}>═</button></div><button onClick={()=>create('text',null)}><MessageSquare size={17}/>整篇笔记</button><button onClick={()=>setPanel(!panel)}><NotebookPen size={17}/>笔记 {notes.length}</button></div>{pen&&<p className="note-hint">用笔或鼠标从词句开头划到结尾，松开后选择批注。完成后切回「阅读 / 选词」滚动正文。</p>}
 <div className="notebook-columns"><div className="annotated-content"><div ref={root} style={{touchAction:pen?'none':'auto'}} onPointerDown={e=>{if(!pen||e.pointerType==='touch'||penPointer.current!==null)return;e.preventDefault();penPointer.current=e.pointerId;penStart.current=caret(e.clientX,e.clientY);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{if(!pen||e.pointerId!==penPointer.current||!penStart.current||!root.current)return;penPointer.current=null;const end=caret(e.clientX,e.clientY),start=penStart.current;penStart.current=null;if(!end||!root.current.contains(start.startContainer)||!root.current.contains(end.startContainer))return;try{const r=document.createRange();if(start.compareBoundaryPoints(Range.START_TO_START,end)<=0){r.setStart(start.startContainer,start.startOffset);r.setEnd(end.startContainer,end.startOffset);}else{r.setStart(end.startContainer,end.startOffset);r.setEnd(start.startContainer,start.startOffset);}const a=captureAnchor(root.current,r);if(a.quote.trim())setSelection(a);}catch{setError('请从文字开头划到结尾重试');}}} onPointerCancel={()=>{penPointer.current=null;penStart.current=null;}}>{children}</div><div className="note-marks" aria-hidden="true">{marks.map((m,i)=><span className={'mark-'+m.mark} key={i} style={{left:m.x,top:m.y,width:m.w,height:m.h}}/>)}</div></div>
 {panel&&<aside ref={side} className="notes-workspace"><header><div><NotebookPen size={20}/><strong>阅读笔记</strong></div><button aria-label="收起笔记区" onClick={()=>setPanel(false)}><X size={18}/></button></header><Tabs value={tab} onValueChange={setTab}><TabsList className="w-full"><TabsTrigger value="notes">文字</TabsTrigger><TabsTrigger value="draft">草稿</TabsTrigger><TabsTrigger value="audio">录音</TabsTrigger><TabsTrigger value="ai">问 AI</TabsTrigger></TabsList></Tabs>{error&&<p className="ai-error" role="alert">{error}<button onClick={()=>void load()}>重试读取</button></p>}
 {tab==='ai'?<div className="note-editor"><blockquote>{askQuote?.quote||'未选择词句，当前将按一般问题回答。'}</blockquote><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="结合这段内容，我想问…" rows={4}/><button className="primary" disabled={aiBusy||!question.trim()} onClick={()=>void ask()}>{aiBusy?'正在回答…':'发送给 AI'}</button><button className="subtle" onClick={onConfigure}>AI 设置</button>{answer&&<div className="note-ai-answer">{answer}</div>}</div>:draft?<div className="note-editor"><div className="editor-caption"><small>{dirty?'有未保存修改':notice||'已保存的笔记'}</small><button onClick={()=>{if(discard()){setDraft(null);setDirty(false);setClip(null);}}}>关闭编辑</button></div><blockquote>{draft.quote||'整篇文章笔记'}</blockquote><label className="field">原文标记<select disabled={saving} value={draft.mark||'underline'} onChange={e=>change({mark:e.target.value})}><option value="underline">下划线</option><option value="highlight">荧光高亮</option><option value="wavy">波浪线</option><option value="double">双下划线</option></select></label>{tab==='notes'&&<textarea disabled={saving} value={draft.text} maxLength={20000} onChange={e=>change({text:e.target.value})} rows={8} placeholder="写下理解、问题，或给未来的自己留一句话…"/>}{tab==='draft'&&<div inert={saving}><InkPaper key={draft.id} strokes={draft.strokes} onChange={strokes=>change({strokes})}/></div>} {tab==='audio'&&<div className="voice-editor"><Mic size={34}/><p>{recording?'正在录音，最长 5 分钟':'把此刻的想法录下来'}</p><button className="primary" disabled={saving} onClick={()=>recording?rec.current?.stop():void record()}>{recording?'停止录音':'开始录音'}</button><label className="field">或上传已有录音<input type="file" accept="audio/*" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>12000000)setError('录音请小于 12 MB');else {setClip(f);setDirty(true);}}}}/></label>{(clipUrl||draft.hasAudio)&&(clipUrl?<audio controls src={clipUrl}/>:<NoteAudio id={draft.id}/>)}</div>}<div className="note-save-row"><span>{draft.text?'文字 · ':''}{draft.strokes.length?'手写 · ':''}{draft.hasAudio||clip?'录音':''}</span><button className="primary" disabled={busy||!dirty} onClick={()=>void save()}>{saving?<Loader2 size={16} className="spin"/>:!dirty?<Check size={16}/>:<Save size={16}/>} {saving?'保存中…':dirty?'保存笔记':'已保存'}</button></div></div>:<div className="note-start"><NotebookPen size={30}/><p>选中原文词句，或为整篇文章添加笔记。</p><button className="primary" onClick={()=>create(tab==='draft'?'draft':tab==='audio'?'audio':'text',null)}>新建{tab==='draft'?'草稿':tab==='audio'?'录音':'笔记'}</button></div>}
 <div className="saved-notes"><h3>本篇已保存 <span>{notes.length}</span></h3>{loading&&<p>正在读取…</p>}{notes.map(n=><section key={n.id} className={'note-card '+(draft?.id===n.id?'active-note':'')}><button className="note-quote" onClick={()=>locate(n)}>{n.quote||'整篇文章'}</button>{n.text&&<p>{n.text}</p>}{n.strokes.length>0&&<InkPreview strokes={n.strokes}/>} {n.hasAudio&&<NoteAudio id={n.id}/>}<div><button onClick={()=>{if(discard()){setDraft(n);setClip(null);setDirty(false);setError('');setTab(n.kind==='draft'?'draft':n.kind==='audio'?'audio':'notes');side.current?.scrollTo({top:0,behavior:'smooth'});}}}>编辑</button><button onClick={e=>{const selection=window.getSelection(),inside=!!selection?.anchorNode&&e.currentTarget.closest('section')?.contains(selection.anchorNode);const quote=inside?selection!.toString().slice(0,2000):n.quote?.slice(0,2000);const paragraph=e.currentTarget.closest('section')?.querySelector('p');let anchor:Partial<Anchor>={start:n.start,end:n.end,prefix:n.prefix,suffix:n.suffix};if(paragraph&&selection?.rangeCount&&paragraph.contains(selection.anchorNode)&&paragraph.contains(selection.focusNode))anchor=captureAnchor(paragraph,selection.getRangeAt(0));void copyReference({...anchor,kind:'note',id:n.id,article:n.article,label:n.text.slice(0,100)||'阅读笔记',quote,view:n.view,field:inside&&quote&&n.text.includes(quote)?'text':'quote'}).then(()=>toast.success('笔记链接已复制，可粘贴到自由笔记')).catch(()=>toast.error('复制失败'));}}>复制链接</button><button onClick={()=>void remove(n)}>删除</button><small>{n.view==='original'?'原文':'译文'} · {n.updated?new Date(n.updated).toLocaleDateString():''}</small></div></section>)}</div><button className="notebook-account" onClick={()=>{setRecovery(true);setCode('');setAccountMessage('');}}><Link2 size={16}/>笔记本恢复与跨设备访问</button></aside>}</div>
 {selection&&<div className="annotation-selection" role="toolbar" aria-label="所选文字操作"><span>“{selection.quote.slice(0,38)}”</span><button disabled={busy||loading} onClick={()=>create('underline')}><Underline size={16}/>标记</button><button disabled={busy||loading} onClick={()=>create('text')}><MessageSquare size={16}/>文字</button><button disabled={busy||loading} onClick={()=>create('draft')}><PenLine size={16}/>草稿</button><button disabled={busy||loading} onClick={()=>create('audio')}><Mic size={16}/>录音</button><button onClick={()=>void copyReference({...selection,kind:'article',id:article,article,label:selection.quote.slice(0,100),quote:selection.quote.slice(0,2000),view}).then(()=>toast.success('选中片段的链接已复制')).catch(()=>toast.error('复制失败'))}><Link2 size={16}/>片段链接</button><button disabled={busy} onClick={openAI}><Sparkles size={16}/>问 AI</button><button aria-label="取消选词" onClick={()=>{setSelection(null);window.getSelection()?.removeAllRanges();}}><X size={16}/></button></div>}
 <Dialog open={recovery} onOpenChange={setRecovery}><DialogContent className="app-dialog"><DialogTitle>打开同一本笔记</DialogTitle><DialogDescription>恢复码可以在其他设备访问这本笔记。请自己保存，持有码的人也能访问。</DialogDescription><button className="subtle" onClick={async()=>{try{const r=await notesFetch('/api/notebook?recovery=1');const d=await r.json();if(!r.ok)throw new Error('读取恢复码失败');setCode(d.code);}catch(e){setAccountMessage((e as Error).message);}}}>显示当前笔记本恢复码</button>{code&&<><textarea aria-label="当前恢复码" readOnly value={code} rows={3}/><button onClick={async()=>{try{await navigator.clipboard.writeText(code);setAccountMessage('已复制');}catch{setAccountMessage('请长按上方恢复码手动复制');}}}>复制恢复码</button></>}<label className="field">从另一台设备打开<input type="password" autoComplete="off" value={restoreCode} onChange={e=>setRestoreCode(e.target.value.trim())} placeholder="粘贴已保存笔记本的恢复码"/></label><button className="primary" disabled={busy||!restoreCode} onClick={async()=>{if(!discard())return;try{const r=await notesFetch('/api/notebook',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:restoreCode})});const d=await r.json();if(!r.ok)throw new Error(d.error);setDraft(null);setDirty(false);setRecovery(false);setRestoreCode('');await load();}catch(e){setAccountMessage((e as Error).message);}}}>打开笔记本</button>{accountMessage&&<p role="status">{accountMessage}</p>}<p className="note-hint">恢复笔记不包含订阅列表；订阅可通过 OPML 导入。不同设备编辑后，重新打开文章读取最新笔记。</p></DialogContent></Dialog></div>;
}
