'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,Plus,Check,Loader2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {RSSHubInstances} from '@/components/rsshub-instances';
import {rsshubUrl} from '@/lib/rsshub';
import {biliUid,biliStarters,type BiliCreator} from '@/lib/bilibili';
export function BilibiliDirectory({instance,onInstance,subscribed,onSubscribe}:{instance:string;onInstance:(v:string)=>void;subscribed:string[];onSubscribe:(url:string,category:string)=>Promise<boolean>}){
 const [query,setQuery]=useState(''),[mode,setMode]=useState('starters'),[creators,setCreators]=useState<BiliCreator[]>(biliStarters),[error,setError]=useState(''),[at,setAt]=useState(''),[busy,setBusy]=useState(false),[adding,setAdding]=useState(''),[selectedUid,setSelectedUid]=useState('946974'),[kind,setKind]=useState('video');const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 async function load(next:string){controller.current?.abort();setMode(next);setError('');setAt('');if(next==='starters'){setCreators(biliStarters);setBusy(false);return;}const uid=biliUid(query);if(next==='search'&&uid){setCreators([{uid,name:'UP '+uid,description:'来自你填写的 UID / 主页链接，添加时读取订阅验证'}]);setSelectedUid(uid);setBusy(false);return;}const ctl=new AbortController();controller.current=ctl;setBusy(true);setCreators([]);try{const r=await fetch('/api/bilibili?mode='+next+'&q='+encodeURIComponent(query.trim()),{signal:ctl.signal,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);if(!ctl.signal.aborted){setCreators(d.creators);setAt(new Date(d.at).toLocaleString('zh-CN'));if(d.creators[0])setSelectedUid(d.creators[0].uid);}}catch(e){if(!ctl.signal.aborted)setError((e as Error).message);}finally{if(!ctl.signal.aborted)setBusy(false);}}
 function route(uid:string){return '/bilibili/user/'+kind+'/'+uid;}
 function address(uid:string){try{return rsshubUrl(instance,route(uid));}catch{return '';}}
 async function subscribe(c:BiliCreator){if(adding)return;setSelectedUid(c.uid);setAdding(c.uid);setError('');try{const url=address(c.uid);if(!url)throw new Error('请填写有效的 RSSHub 实例');if(!await onSubscribe(url,'B站'))setError('当前实例未能读取这个 UP 主的订阅。可以在下方检测其他实例后重试。');}catch(e){setError((e as Error).message);}finally{setAdding('');}}
 return <section className="bili-directory"><form className="directory-search" onSubmit={e=>{e.preventDefault();void load('search');}}><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索 UP 主名称，或粘贴 UID / 主页链接" aria-label="搜索 B 站 UP 主"/></label><button className="primary" disabled={busy||!query.trim()}>搜索</button></form><Tabs value={mode} onValueChange={v=>void load(v)}><TabsList className="w-full"><TabsTrigger value="starters">入门推荐</TabsTrigger><TabsTrigger value="search" disabled={!query.trim()}>搜索结果</TabsTrigger><TabsTrigger value="popular">综合热门作者</TabsTrigger><TabsTrigger value="ranking">排行榜作者</TabsTrigger></TabsList></Tabs><div className="directory-meta"><span>{busy?'正在读取 B 站…':mode==='starters'?'编辑选入，不是实时排名':mode==='search'?'按 B 站搜索结果选择 UP 主':'按热门／榜单视频顺序去重展示作者'}</span><Select value={kind} onValueChange={setKind}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="video">订阅视频</SelectItem><SelectItem value="article">订阅图文</SelectItem></SelectContent></Select></div>{error&&<div className="ai-error" role="alert">{error}<p>实时查询受 B 站访问限制时，可使用 UID / 主页链接，或切换「入门推荐」。</p></div>}{at&&<p className="privacy">数据获取时间：{at}</p>}<div className="directory-grid">{creators.map(c=>{const added=subscribed.includes(address(c.uid));return <div className="directory-card" key={c.uid}><strong>{c.rank?`${c.rank}. `:''}{c.name}</strong><small>UID {c.uid}{c.fans!==undefined?' · '+c.fans.toLocaleString()+' 粉丝':''}</small><p>{c.video||c.description}</p><a href={'https://space.bilibili.com/'+c.uid} target="_blank" rel="noreferrer">核对主页</a><button className="subtle" disabled={!!adding||added} onClick={()=>subscribe(c)}>{added?<Check size={15}/>:adding===c.uid?<Loader2 size={15} className="spin"/>:<Plus size={15}/>} {added?'已订阅':adding===c.uid?'正在验证…':'一键订阅'}</button></div>;})}</div>{!busy&&!error&&!creators.length&&<p className="privacy">没有找到 UP 主，试试完整昵称或主页链接。</p>}<details className="bili-instance"><summary>RSSHub 实例与路由检测</summary><label className="field">当前实例<input type="url" value={instance} onChange={e=>onInstance(e.target.value)}/></label><label className="field">检测用 UP 主 UID<input value={selectedUid} onChange={e=>setSelectedUid(e.target.value.replace(/\D/g,''))}/></label><RSSHubInstances route={selectedUid?route(selectedUid):''} value={instance} onChange={onInstance}/></details><p className="privacy">视频与图文订阅通过 RSSHub 获取，所选实例可能需要配置 B 站登录信息。这里不会代你登录 B 站；读取失败时会保留已有订阅。<a href="https://docs.rsshub.app/routes/social-media" target="_blank" rel="noreferrer">RSSHub 路由文档</a></p></section>;
}
