'use client';
import {useState,useRef,useEffect} from 'react';
import data from '@/lib/discovery-data.json';
import {buildDiscoveryRoute,discoveryCategories,type DiscoveryRoute} from '@/lib/discovery';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {feedCatalog} from '@/lib/feed-catalog';
const platforms=[...data.platforms,{key:"thelancet",name:"柳叶刀 The Lancet",host:"thelancet.com",categories:["journal"],routes:[]}];
export function DiscoveryDirectory({onSubscribe,onConfigureHub}:{onSubscribe:(url:string,category:string)=>Promise<boolean>;onConfigureHub:(route:string)=>void}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('全部'),[page,setPage]=useState(0),[active,setActive]=useState(''),[routeIndex,setRouteIndex]=useState('0'),[values,setValues]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const configRef=useRef<HTMLElement>(null);useEffect(()=>{if(active)configRef.current?.scrollIntoView({block:'start',behavior:'smooth'});},[active]);
 const q=query.trim().toLowerCase(),categories=[...new Set(platforms.flatMap(p=>p.categories))].filter(c=>c!=='popular');
 const rows=platforms.filter(p=>(category==='全部'||p.categories.includes(category))&&(!q||[p.name,p.key,p.host,...p.routes.map(r=>r.name)].join(' ').toLowerCase().includes(q)));
 const platform=platforms.find(p=>p.key===active),route=platform?.routes[Number(routeIndex)] as DiscoveryRoute|undefined;
 let generated='',problem='';if(route)try{generated=buildDiscoveryRoute(route,values);}catch(e){problem=(e as Error).message;}
 async function add(url:string,cat:string){setBusy(true);setMessage('');try{setMessage(await onSubscribe(url,cat)?'已添加订阅':'暂时无法读取。可选择其他实例重试；有些平台需要在实例上配置登录信息。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="discovery-directory"><p className="privacy">Folo 公开平台目录 · {data.date} 快照。另补充柳叶刀期刊入口。平台需要选择具体栏目或作者；不含 Folo 私人订阅和专用服务。</p><div className="directory-search"><label className="field">搜索平台或订阅内容<input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="例如：Nature、哔哩哔哩、YouTube、新闻"/></label><Select value={category} onValueChange={v=>{setCategory(v);setPage(0);}}><SelectTrigger aria-label="平台分类"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="全部">全部分类</SelectItem>{categories.map(c=><SelectItem key={c} value={c}>{discoveryCategories[c]||c}</SelectItem>)}</SelectContent></Select></div>
 {platform&&<section ref={configRef} className="discovery-config"><header><h3>{platform.name}</h3><button disabled={busy} onClick={()=>{setActive('');setMessage('');}}>关闭配置</button></header>{feedCatalog.filter(f=>{try{return (platform.key==='thelancet'&&new URL(f.url).hostname==='api.crossref.org')||new URL(f.url).hostname.replace(/^www\./,'')===platform.host.replace(/^www\./,'');}catch{return false;}}).map(f=><button className="subtle" key={f.url} disabled={busy} onClick={()=>void add(f.url,f.category)}>添加订阅 · {f.name}</button>)}{platform.routes.length>0?<><label className="field">选择订阅内容<Select value={routeIndex} onValueChange={v=>{setRouteIndex(v);setValues({});setMessage('');}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{platform.routes.map((r,i)=><SelectItem key={r.path} value={String(i)}>{r.name} · {r.path}</SelectItem>)}</SelectContent></Select></label>{route?.params.map(p=><label className="field" key={route.path+p.key}>{p.label} {p.optional?'（可选）':'（必填）'}<input value={values[p.key]??p.default} onChange={e=>setValues(v=>({...v,[p.key]:e.target.value}))} placeholder={p.key} maxLength={1000}/>{p.options.length>0&&<small>可选值：{p.options.slice(0,12).map(o=>`${o.label}=${o.value}`).join('；')}</small>}</label>)}{route?.example&&<small>文档示例：{route.example}</small>}{route?.requirements.length? <p className="instance-warning">{route.requirements.join(' · ')}。凭据由实例维护者配置，请勿填进订阅地址。</p>:null}<p className="hub-preview">{generated?'rsshub:/'+generated:problem}</p><div className="discovery-actions"><button className="primary" disabled={busy||!generated} onClick={()=>void add('rsshub:/'+generated,discoveryCategories[platform.categories.find(c=>c!=='popular')||'other']||'其他')}>{busy?'正在读取…':'使用当前实例订阅'}</button><button className="subtle" disabled={busy||!generated} onClick={()=>onConfigureHub(generated)}>选择 / 检测其他实例</button></div></>:<p>可优先使用上方订阅入口；未列出的栏目请查看来源文档。</p>}{message&&<p role="status">{message}</p>}<a className="hub-doc" href={platform.key==='thelancet'?'https://www.thelancet.com/content/rss':'https://github.com/DIYgod/RSSHub/tree/master/lib/routes/'+encodeURIComponent(platform.key)} target="_blank" rel="noreferrer">查看此平台官方路由资料</a></section>}
 <div className="directory-meta"><span>{rows.length} / {platforms.length} 个平台 · {data.platforms.reduce((n,p)=>n+p.routes.length,0)} 个配置入口</span></div><div className="directory-grid">{rows.slice(page*36,(page+1)*36).map(p=><article className="directory-card" key={p.key}><strong>{p.name}</strong><p>{p.host}</p><small>{p.categories.filter(c=>c!=='popular').map(c=>discoveryCategories[c]||c).join(' · ')}</small><button className="subtle" onClick={()=>{setActive(p.key);setRouteIndex('0');setValues({});setMessage('');}}>{p.routes.length?`选择订阅内容（${p.routes.length}）`:'查看订阅入口'}</button></article>)}</div><div className="discovery-actions"><button className="subtle" disabled={page===0} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page+1} / {Math.max(1,Math.ceil(rows.length/36))}</span><button className="subtle" disabled={(page+1)*36>=rows.length} onClick={()=>setPage(p=>p+1)}>下一页</button></div><p className="privacy">公开目录不代表全部实时可用。未收录成人内容；需要登录或付费的来源依发布方权限访问。社区推荐与热门榜单会变化，本页不将静态快照标为实时排名。</p></section>;
}
