'use client';
import {useState} from 'react';
import {parseOPML,exportOPML,type Feed} from '@/lib/feed-reader';
import {downloadFile} from '@/lib/downloads';
export function FeedManager({feeds,onChange,onSubscribe}:{feeds:Feed[];onChange:(feeds:Feed[])=>void;onSubscribe:(url:string,category:string)=>Promise<boolean>}){
 const [preview,setPreview]=useState<Feed[]>([]),[chosen,setChosen]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 async function download(){setBusy(true);try{const saved=await downloadFile(new Blob([exportOPML(feeds)],{type:'text/xml'}),'yueliu-feeds.opml');setStatus(saved?'OPML 已导出':'已取消导出');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
 async function importFeeds(){setBusy(true);let ok=0;for(const f of preview.filter(x=>chosen.has(x.url))){setStatus('正在导入：'+f.name);if(await onSubscribe(f.url,f.category||'导入'))ok++;}setStatus(`已添加 ${ok} 个，失败 ${chosen.size-ok} 个；原有订阅保留。`);setBusy(false);}
 return <section className="feed-manager"><div className="manager-actions"><label className="subtle">导入 OPML<input type="file" accept=".opml,.xml" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>2000000)throw new Error('文件请小于 2 MB');const rows=parseOPML(await file.text());setPreview(rows);setChosen(new Set(rows.map(x=>x.url)));setStatus(rows.length?'已解析，可选择需要导入的订阅':'文件中未发现订阅');}catch(e){setStatus((e as Error).message);}}}/></label><button className="subtle" disabled={busy} onClick={download}>导出 OPML</button></div>{status&&<p role="status">{status}</p>}{preview.length>0&&<div className="opml-preview">{preview.map(f=><label key={f.url}><input type="checkbox" checked={chosen.has(f.url)} disabled={busy} onChange={e=>setChosen(s=>{const n=new Set(s);if(e.target.checked)n.add(f.url);else n.delete(f.url);return n;})}/><span>{f.name}<small>{f.category}</small></span></label>)}<button className="primary" disabled={busy||!chosen.size} onClick={()=>void importFeeds()}>{busy?'导入中…':`导入选中的 ${chosen.size} 个订阅`}</button></div>}<h3>我的订阅 · {feeds.length}</h3><p className="privacy">名称与分组修改后立即保存。网页规则不导出为 OPML。</p>{feeds.map(f=><div className="managed-feed" key={f.id}><input aria-label="订阅名称" value={f.name} onChange={e=>onChange(feeds.map(x=>x.id===f.id?{...x,name:e.target.value}:x))}/><input aria-label="订阅分组" value={f.category||''} placeholder="分组名称" onChange={e=>onChange(feeds.map(x=>x.id===f.id?{...x,category:e.target.value}:x))}/><select aria-label="内容分区" value={f.view||'auto'} onChange={e=>onChange(feeds.map(x=>x.id===f.id?{...x,view:e.target.value}:x))}><option value="auto">自动识别类型</option><option value="article">文章</option><option value="video">视频</option><option value="audio">音频</option><option value="image">图片</option></select><small>{f.url}</small></div>)}</section>;
}
