'use client';
import {apiFetch} from '@/lib/api-client';
import {useState} from 'react';
import {Search,Plus,Check,Loader2} from 'lucide-react';
import {feedCatalog,feedCategories,searchCatalog,type CatalogFeed} from '@/lib/feed-catalog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export function FeedDirectory({subscribed,onSubscribe}:{subscribed:string[];onSubscribe:(url:string,category:string)=>Promise<boolean>}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('全部'),[language,setLanguage]=useState('全部'),[busy,setBusy]=useState(''),[selected,setSelected]=useState<string[]>([]),[note,setNote]=useState('');const rows=searchCatalog(query,category,language);
 async function add(items:CatalogFeed[]){if(busy)return;let ok=0,failed=0;const failures:string[]=[];for(const item of items){if(subscribed.includes(item.url))continue;setBusy(item.url);try{if(await onSubscribe(item.url,item.category))ok++;else{failed++;failures.push(item.name);}}catch{failed++;failures.push(item.name);}}setBusy('');setNote(`已添加 ${ok} 个订阅${failed?'，'+failed+' 个暂时无法读取：'+failures.join('、'):''}`);setSelected([]);}
 return <section className="feed-directory"><div className="directory-search"><label className="search"><Search size={17}/><input aria-label="搜索订阅目录" placeholder="搜索网站、主题或网址…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select value={language} onValueChange={setLanguage}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['全部','中文','English'].map(l=><SelectItem value={l} key={l}>{l==='全部'?'所有语言':l}</SelectItem>)}</SelectContent></Select></div><div className="category-chips" aria-label="订阅分类">{feedCategories.map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="directory-meta"><span>{rows.length} / {feedCatalog.length} 个订阅源</span><button className="subtle" disabled={!!busy||!selected.length} onClick={()=>add(feedCatalog.filter(x=>selected.includes(x.url)))}>{busy?'正在添加…':`添加已选（${selected.length}）`}</button></div>{note&&<p role="status" className="test-result">{note}</p>}<div className="directory-grid">{rows.map(x=>{const added=subscribed.includes(x.url);return <div className="directory-card" key={x.url}><label className="directory-check"><input type="checkbox" aria-label={'选择 '+x.name} checked={selected.includes(x.url)} disabled={added||!!busy} onChange={e=>setSelected(v=>e.target.checked?[...v,x.url]:v.filter(u=>u!==x.url))}/><strong>{x.name}</strong></label><p>{x.description}</p><small>{x.category} · {x.language}</small><button className="subtle" disabled={added||!!busy} onClick={()=>add([x])}>{added?<Check size={15}/>:busy===x.url?<Loader2 className="spin" size={15}/>:<Plus size={15}/>} {added?'已订阅':'一键添加'}</button></div>;})}</div>{!rows.length&&<p className="privacy">没有匹配的订阅，可以切换到「RSS / 网站」添加自己的地址。</p>}<p className="privacy">添加时会实际读取订阅源。目录不是实时可用性保证；全文范围由发布方决定。</p></section>;
}
