'use client';
import {useEffect,useState} from 'react';
import {Download,Wifi,WifiOff,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {localAll,localGet} from '@/lib/local-store';
import {syncNotes,type StoredNote} from '@/lib/notes-client';
import {isNative,serviceBase} from '@/lib/api-client';
import {exportBackup,importBackup,downloadFile} from '@/lib/offline';
import {toast} from 'sonner';
export function OfflineSettings(){const [open,setOpen]=useState(false),[online,setOnline]=useState(true),[status,setStatus]=useState(''),[pending,setPending]=useState(0),[native,setNative]=useState(false),[service,setService]=useState(''),[busy,setBusy]=useState(false),[install,setInstall]=useState<any>(null),[error,setError]=useState(''),[ready,setReady]=useState(false);
 async function state(){setPending((await localAll<StoredNote>('notes')).filter(n=>n.dirty).length);setError(await localGet<string>('meta','notes-sync-error')||'');}
 useEffect(()=>{const native=isNative();setNative(native);setService(serviceBase());setOnline(navigator.onLine);const network=()=>{setOnline(navigator.onLine);if(navigator.onLine)void syncNotes().catch(()=>{});};window.addEventListener('online',network);window.addEventListener('offline',network);window.addEventListener('yueliu-notes-updated',state);const installHandler=(e:Event)=>{e.preventDefault();setInstall(e);};window.addEventListener('beforeinstallprompt',installHandler);void state();if(!native&&'serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).then(async()=>{await navigator.serviceWorker.ready;setReady(true);}).catch(()=>setStatus('离线应用准备失败，请联网后重试'));const timer=setInterval(()=>{if(navigator.onLine)void syncNotes().catch(()=>{});},60000);return()=>{clearInterval(timer);window.removeEventListener('online',network);window.removeEventListener('offline',network);window.removeEventListener('yueliu-notes-updated',state);window.removeEventListener('beforeinstallprompt',installHandler);};},[]);
 return <><button className="settings-button" onClick={()=>{setOpen(true);void state();}}>{online?<Download size={17}/>:<WifiOff size={17}/>}离线与客户端{!online&&<span>离线中</span>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog offline-dialog"><DialogTitle>随时打开，继续思考</DialogTitle><DialogDescription>已保存的文章、译文、笔记与画布支持离线使用。更新订阅、抓取全文、在线翻译和 AI 需要联网。</DialogDescription><div className="offline-summary">{online?<Wifi size={22}/>:<WifiOff size={22}/>}<div><strong>{online?'当前已联网':'当前离线'}</strong><p>{native?'笔记保存在本机，可用备份迁移':pending?`${pending} 条笔记等待同步`:'本机修改已同步'} · {native?'应用已内置':ready?'离线页面已准备':'正在准备离线页面'}</p></div></div>{!native&&<button className="subtle" disabled={busy||!online} onClick={async()=>{setBusy(true);try{await syncNotes();await state();setStatus('同步完成');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}}><RefreshCw size={16}/>立即同步笔记</button>}{error&&!native&&<p className="ai-error">{error}。本机副本仍然保留。</p>}{install&&<button className="primary" onClick={async()=>{await install.prompt();setInstall(null);}}>安装到这台设备</button>}<div className="offline-section"><h3>备份与迁移</h3><p>包含已保存文章、译文、文字、手写、已下载录音和自由笔记。API 密钥不会导出；文章图片需在目标设备重新下载。</p><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{downloadFile(await exportBackup(),'yueliu-backup-'+new Date().toISOString().slice(0,10)+'.json');setStatus('备份已导出');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}}>导出离线备份</button><label className="field">从网页版 / 其他客户端导入<input type="file" accept="application/json,.json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const n=await importBackup(file);toast.success(`已导入 ${n} 条笔记，正在重新打开`);location.reload();}catch(err){setStatus((err as Error).message);}finally{setBusy(false);e.target.value='';}}}/></label></div><div className="offline-section"><h3>Windows / Android 客户端</h3><p>客户端内置阅读与笔记页面，首次启动也可断网创建笔记。安装包在 GitHub 打包任务完成后提供。</p><a className="hub-doc" href="https://github.com/Tx13758627780/yueliu-reader/actions/workflows/native-build.yml" target="_blank" rel="noreferrer">打开安装包构建与下载 ↗</a><small>Windows 提供 EXE 安装版与便携版；Android 提供可安装的测试 APK。</small></div>{native&&<label className="field">在线服务地址<input type="url" value={service} onChange={e=>setService(e.target.value)}/><small>Android 联网功能使用此服务，也可填写你部署的阅流 HTTPS 地址。Windows 使用内置服务。</small><button className="subtle" onClick={()=>{try{const u=new URL(service);if(u.protocol!=='https:'||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw new Error();localStorage.setItem('yueliu-service',u.origin);toast.success('在线服务已保存');}catch{toast.error('请填写 HTTPS 网站根地址');}}}>保存在线服务</button></label>}{status&&<p role="status">{status}</p>}<p className="privacy">在文章工具栏点「离线保存」下载正文图片和已有录音。音视频节目、登录后内容不会自动下载。</p></DialogContent></Dialog></>;
}
