'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Sparkles,Send,X,Loader2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Selection={text:string;context:string};
export function SelectionAsk({children,onAsk,onConfigure}:{children:ReactNode;onAsk:(quote:string,question:string,context:string)=>Promise<string>;onConfigure:()=>void}){
 const root=useRef<HTMLDivElement>(null);const [selection,setSelection]=useState<Selection|null>(null),[open,setOpen]=useState(false),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{function capture(){if(open||busy)return;const s=window.getSelection();if(!s||s.isCollapsed||!root.current?.contains(s.anchorNode)||!root.current?.contains(s.focusNode))return;const text=s.toString().trim();if(!text)return;const node=s.anchorNode instanceof Element?s.anchorNode:s.anchorNode?.parentElement;setSelection({text:text.slice(0,2000),context:(node?.closest('p,li,blockquote,section')?.textContent||text).slice(0,6000)});}
 document.addEventListener('selectionchange',capture);return()=>document.removeEventListener('selectionchange',capture);},[open,busy]);
 async function ask(){if(busy||!selection||!question.trim())return;setBusy(true);setError('');setAnswer('');try{setAnswer(await onAsk(selection.text,question,selection.context));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div ref={root} className="selectable-article">{children}</div>{selection&&<div className="selection-tools"><span>“{selection.text.slice(0,60)}{selection.text.length>60?'…':''}”</span><button disabled={busy} onClick={()=>{setAnswer('');setError('');setQuestion('');setOpen(true);}}><Sparkles size={16}/>引用问 AI</button><button aria-label="取消选词" onClick={()=>{setSelection(null);window.getSelection()?.removeAllRanges();}}><X size={16}/></button></div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog quote-dialog"><DialogTitle>引用文字问 AI</DialogTitle><DialogDescription>只发送所选词句、附近上下文和你的问题。</DialogDescription><blockquote className="quoted-text">{selection?.text}</blockquote><form onSubmit={e=>{e.preventDefault();void ask();}}><label className="field">你的问题<textarea autoFocus value={question} onChange={e=>setQuestion(e.target.value)} placeholder="例如：这几个词在这里是什么意思？为什么这样表达？" maxLength={2000} rows={3}/></label><div className="quote-actions"><button type="button" disabled={busy} onClick={()=>setQuestion('请解释这几个词在这里的含义和用法。')}>解释含义</button><button type="button" disabled={busy} onClick={()=>setQuestion('请翻译这段引用，并说明上下文中的意思。')}>翻译引用</button><button type="submit" className="primary" disabled={busy||!question.trim()}>{busy?<Loader2 size={16} className="spin"/>:<Send size={16}/>} {busy?'正在回答…':'发送问题'}</button></div></form>{error&&<p role="alert" className="ai-error">{error}</p>}{answer&&<div className="quote-answer prose" aria-live="polite">{answer.split(/\n\n+/).map((p,i)=><p key={i}>{p}</p>)}</div>}<button className="subtle" disabled={busy} onClick={()=>{setOpen(false);onConfigure();}}>AI 设置</button></DialogContent></Dialog></>;
}
