'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {translationLanguages,translationNames,type TranslationConfig} from '@/lib/translation';
export function TranslationSettings({open,onOpenChange,value,onChange,onSave,onTest,onAISettings}:{open:boolean;onOpenChange:(v:boolean)=>void;value:TranslationConfig;onChange:(v:TranslationConfig)=>void;onSave:()=>void;onTest:()=>Promise<string>;onAISettings:()=>void}){
 const [busy,setBusy]=useState(false),[result,setResult]=useState('');const change=(patch:Partial<TranslationConfig>)=>{onChange({...value,...patch});setResult('');};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="app-dialog settings-dialog"><DialogTitle>翻译设置</DialogTitle><DialogDescription>全文翻译使用这里的服务。总结和问答仍使用 AI 设置。</DialogDescription><div className="field">翻译服务<Select value={value.provider} onValueChange={provider=>change({provider:provider as TranslationConfig['provider']})}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(translationNames).map(([id,name])=><SelectItem value={id} key={id}>{name}</SelectItem>)}</SelectContent></Select></div><div className="field">目标语言<Select value={value.target} onValueChange={target=>change({target})}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{translationLanguages.map(l=><SelectItem value={l} key={l}>{l}</SelectItem>)}</SelectContent></Select></div>{value.provider==='ai'?<button className="subtle" onClick={onAISettings}>配置 AI 模型与密钥</button>:<><label className="field">{translationNames[value.provider]} API 密钥<input type="password" autoComplete="off" value={value.provider==='google'?value.googleKey:value.deeplKey} onChange={e=>change(value.provider==='google'?{googleKey:e.target.value}:{deeplKey:e.target.value})}/></label>{value.provider==='deepl'&&<div className="field">DeepL API 方案<Select value={value.deeplPlan} onValueChange={plan=>change({deeplPlan:plan as 'free'|'pro'})}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="free">DeepL API Free</SelectItem><SelectItem value="pro">DeepL API Pro</SelectItem></SelectContent></Select></div>}<a className="hub-doc" target="_blank" rel="noreferrer" href={value.provider==='google'?'https://console.cloud.google.com/apis/library/translate.googleapis.com':'https://www.deepl.com/your-account/keys'}>{value.provider==='google'?'开通 Google Cloud Translation 并获取密钥':'查看 DeepL API 密钥'}</a><p className="privacy">需要该服务的 API 账户及可用额度。网页版翻译账号不一定包含 API 权限。</p></>}{value.provider!=='google'&&<div className="field">表达风格<Select value={value.style} onValueChange={style=>change({style:style as 'natural'|'faithful'})}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="natural">自然流畅，保留含义与术语</SelectItem><SelectItem value="faithful">忠实原文，保留句式</SelectItem></SelectContent></Select></div>}<p className="privacy">{value.provider==='google'?'Google 使用标准神经机器翻译，自动识别原文语言。':'翻译会参考标题和相邻段落；DeepL 优先使用质量模型。'}</p><label className="remember"><Switch checked={value.remember} onCheckedChange={remember=>change({remember})}/><span>在此浏览器记住翻译密钥</span></label><div className="config-tools"><button disabled={busy} onClick={async()=>{setBusy(true);setResult('');try{setResult(await onTest());}catch(e){setResult((e as Error).message);}finally{setBusy(false);}}}>{busy?'正在翻译测试句…':'测试翻译'}</button></div>{result&&<p role="status" className="test-result">{result}</p>}<button className="primary full" onClick={onSave}>保存翻译设置</button></DialogContent></Dialog>;
}
