import {safeFetch,limitedText} from '@/lib/remote';
import {targetCode,decodeTranslation} from '@/lib/translation';
export async function POST(req:Request){try{
 const raw=await req.text();if(raw.length>24000)throw new Error('翻译片段过长');const {provider,key,target,text,context,plan,style}=JSON.parse(raw);
 if(!['google','deepl'].includes(provider))throw new Error('不支持的翻译服务');if(typeof key!=='string'||!key.trim())throw new Error('请在翻译设置中填写该服务的 API 密钥');if(typeof text!=='string'||!text.trim()||text.length>6000)throw new Error('翻译文本为空或过长');
 const signal=AbortSignal.any([req.signal,AbortSignal.timeout(60000)]);let url:string;let headers:Record<string,string>={'Content-Type':'application/json'};let payload:Record<string,unknown>;
 if(provider==='google'){url='https://translation.googleapis.com/language/translate/v2?key='+encodeURIComponent(key.trim());payload={q:text,target:targetCode(target,provider),format:'text',model:'nmt'};}
 else{url=(plan==='pro'?'https://api.deepl.com':'https://api-free.deepl.com')+'/v2/translate';headers.Authorization='DeepL-Auth-Key '+key.trim();payload={text:[text],target_lang:targetCode(target,provider),context:String(context||'').slice(0,6000),preserve_formatting:true,split_sentences:'nonewlines',model_type:'prefer_quality_optimized',custom_instructions:[style==='faithful'?'Stay close to the source phrasing and preserve its facts, terminology, and structure. Do not summarize or omit content.':'Use natural, fluent wording while preserving the meaning, facts, and terminology of the source. Do not summarize or omit content.']};}
 const r=await safeFetch(url,{method:'POST',headers,signal,body:JSON.stringify(payload)});let data:any;try{data=JSON.parse(await limitedText(r));}catch{throw new Error(`翻译服务返回异常内容（HTTP ${r.status}）`);}if(!r.ok){const reason=r.status===403?'密钥无效、API 未启用或账户无权访问':r.status===456?'DeepL 翻译额度已用完':r.status===429?'请求过于频繁，请稍后重试':String(data.error?.message||data.message||'请检查服务设置').slice(0,200);throw new Error(`翻译失败（HTTP ${r.status}）：${reason}`);}
 const answer=provider==='google'?data.data?.translations?.[0]?.translatedText:data.translations?.[0]?.text;if(typeof answer!=='string'||!answer.trim())throw new Error('翻译服务没有返回译文');return Response.json({answer:provider==='google'?decodeTranslation(answer):answer,provider},{headers:{'Cache-Control':'no-store'}});
 }catch(e){const message=e instanceof Error?e.message:'翻译失败';return Response.json({error:/timeout|timed out|aborted/i.test(message)?'翻译服务响应超时，请稍后重试':message},{status:400,headers:{'Cache-Control':'no-store'}});}}
