import {biliCreators} from './bilibili';
import {biliRequest,biliJsonFeed,biliDynamicFeed,BiliError} from './bili-client';
export async function handleBilibili(req:Request){try{
 const p=new URL(req.url).searchParams,mode=p.get('mode')||'search',q=(p.get('q')||'').trim(),page=Math.max(1,Math.min(100,Number(p.get('page'))||1)),uid=p.get('uid')||'',kind=p.get('kind')||'video';const signal=AbortSignal.any([req.signal,AbortSignal.timeout(25000)]);
 if(!['search','popular','ranking','feed'].includes(mode))throw new Error('不支持的 B 站查询');if(mode==='search'&&(!q||q.length>60))throw new Error('请输入 1 至 60 字的 UP 主名称');if(mode==='feed'&&!/^[1-9]\d{0,17}$/.test(uid))throw new Error('UP 主 UID 无效');
 if(mode==='feed'&&!['video','article','dynamic'].includes(kind))throw new Error('不支持的 B 站订阅类型');
 if(mode==='feed'&&kind==='dynamic'){const data=await biliRequest('/x/polymer/web-dynamic/v1/feed/space',{host_mid:uid,offset:'',timezone_offset:'-480'},false,signal);return Response.json(biliDynamicFeed(data,uid,req.url),{headers:{'Cache-Control':'public, max-age=300'}});}
 if(mode==='feed'){const data=await biliRequest(kind==='article'?'/x/space/wbi/article':'/x/space/wbi/arc/search',{mid:uid,pn:'1',ps:'30',order:kind==='article'?'publish_time':'pubdate',platform:'web',web_location:'1550101'},true,signal);return Response.json(biliJsonFeed(data,uid,kind,req.url),{headers:{'Cache-Control':'public, max-age=300'}});}
 const data=mode==='search'?await biliRequest('/x/web-interface/wbi/search/type',{keyword:q,search_type:'bili_user',page:String(page),page_size:'20',platform:'pc',web_location:'1430654',order:['fans','level'].includes(p.get('order')||'')?p.get('order')!:'0',order_sort:'0',user_type:'1'},true,signal):await biliRequest(mode==='ranking'?'/x/web-interface/ranking/v2':'/x/web-interface/popular',mode==='ranking'?{rid:'0',type:'all'}:{pn:String(page),ps:'30'},false,signal);
 return Response.json({creators:biliCreators(data,mode),mode,page,hasMore:mode==='search'?page<Number(data.numPages||1):mode==='popular'&&!data.no_more,at:new Date().toISOString()},{headers:{'Cache-Control':'private, max-age=120'}});
 }catch(e){const err=e as Error;const requestId=crypto.randomUUID();console.error(JSON.stringify({event:'bilibili_read_failed',requestId,code:e instanceof BiliError?e.code:'request_failed',stage:e instanceof BiliError?e.stage:'request'}));return Response.json({requestId,error:/timeout|timed out|aborted/i.test(err.message)?'B 站请求超时，请稍后重试':err.message,code:e instanceof BiliError?e.code:undefined,stage:e instanceof BiliError?e.stage:undefined},{status:502,headers:{'Cache-Control':'no-store'}});}}
