export type CatalogFeed={name:string;url:string;category:string;language:string;description:string};
const rows:string[][]=[
 ['少数派','https://sspai.com/feed','数码科技','中文','数字生活与效率工具'],
 ['爱范儿','https://www.ifanr.com/feed','数码科技','中文','科技产品与消费趋势'],
 ['IT之家','https://www.ithome.com/rss/','数码科技','中文','数码与软件资讯'],
 ['Solidot','https://www.solidot.org/index.rss','数码科技','中文','开源、科学与技术新闻'],
 ['The Verge','https://www.theverge.com/rss/index.xml','数码科技','English','科技与产品报道'],
 ['Ars Technica','https://feeds.arstechnica.com/arstechnica/index','数码科技','English','技术深度报道'],
 ['TechCrunch','https://techcrunch.com/feed/','商业财经','English','创业与科技公司'],
 ['WIRED','https://www.wired.com/feed/rss','数码科技','English','技术与社会'],
 ['BBC · 全球新闻','https://feeds.bbci.co.uk/news/world/rss.xml','新闻时事','English','国际新闻'],
 ['BBC · 科技','https://feeds.bbci.co.uk/news/technology/rss.xml','数码科技','English','科技新闻'],
 ['BBC · 商业','https://feeds.bbci.co.uk/news/business/rss.xml','商业财经','English','商业与经济'],
 ['BBC · 科学环境','https://feeds.bbci.co.uk/news/science_and_environment/rss.xml','科学学术','English','科学与环境新闻'],
 ['The Guardian · 世界','https://www.theguardian.com/world/rss','新闻时事','English','国际报道'],
 ['The Guardian · 商业','https://www.theguardian.com/business/rss','商业财经','English','经济与企业'],
 ['The Guardian · 科技','https://www.theguardian.com/technology/rss','数码科技','English','技术与互联网'],
 ['The Guardian · 图书','https://www.theguardian.com/books/rss','人文生活','English','书评与文学'],
 ['The Guardian · 电影','https://www.theguardian.com/film/rss','影音游戏','English','电影与影评'],
 ['The Guardian · 旅行','https://www.theguardian.com/travel/rss','人文生活','English','旅行与目的地'],
 ['The Guardian · 媒体','https://www.theguardian.com/media/rss','新闻传媒','English','新闻业与传播'],
 ['NASA','https://www.nasa.gov/feed/','科学学术','English','航天与太空探索'],
 ['Nature','https://www.nature.com/nature.rss','科学学术','English','期刊文章与研究'],
 ['Quanta Magazine','https://www.quantamagazine.org/feed/','科学学术','English','数学、物理与生命科学'],
 ['ScienceDaily · 综合','https://www.sciencedaily.com/rss/all.xml','科学学术','English','科学研究新闻'],
 ['ScienceDaily · 健康','https://www.sciencedaily.com/rss/top/health.xml','健康医学','English','健康与医学研究'],
 ['ScienceDaily · 环境','https://www.sciencedaily.com/rss/top/environment.xml','科学学术','English','生态与环境'],
 ['ScienceDaily · 社会','https://www.sciencedaily.com/rss/top/society.xml','人文生活','English','社会科学研究'],
 ['arXiv · 人工智能','https://rss.arxiv.org/rss/cs.AI','AI与开发','English','人工智能论文摘要'],
 ['arXiv · 自然语言','https://rss.arxiv.org/rss/cs.CL','AI与开发','English','语言模型与自然语言处理'],
 ['arXiv · 机器学习','https://rss.arxiv.org/rss/cs.LG','AI与开发','English','机器学习研究'],
 ['arXiv · 计算机视觉','https://rss.arxiv.org/rss/cs.CV','AI与开发','English','图像与视觉研究'],
 ['Hacker News','https://hnrss.org/frontpage','AI与开发','English','技术社区 · hnrss 转换源'],
 ['GitHub Blog','https://github.blog/feed/','AI与开发','English','开发工具与开源'],
 ['Cloudflare Blog','https://blog.cloudflare.com/rss/','AI与开发','English','网络、性能与安全'],
 ['Google Blog','https://blog.google/rss/','数码科技','English','Google 产品与研究动态'],
 ['Mozilla Blog','https://blog.mozilla.org/en/feed/','AI与开发','English','浏览器与开放网络'],
 ['Smashing Magazine','https://www.smashingmagazine.com/feed/','AI与开发','English','前端开发与设计'],
 ['阮一峰的网络日志','https://www.ruanyifeng.com/blog/atom.xml','AI与开发','中文','科技爱好者周刊与技术文章'],
 ['V2EX','https://www.v2ex.com/index.xml','AI与开发','中文','开发者社区话题'],
 ['机核','https://www.gcores.com/rss','影音游戏','中文','游戏与流行文化'],
 ['月光博客','https://www.williamlong.info/rss.xml','新闻传媒','中文','互联网与技术观察'],
 ['NPR · 新闻','https://feeds.npr.org/1001/rss.xml','新闻时事','English','美国公共广播新闻'],
 ['NPR · 科学','https://feeds.npr.org/1007/rss.xml','科学学术','English','科学报道'],
 ['NPR · 音乐','https://feeds.npr.org/1039/rss.xml','影音游戏','English','音乐故事与评论'],
 ['ScienceDaily · 科技','https://www.sciencedaily.com/rss/top/technology.xml','数码科技','English','科技研究新闻']
];
export const feedCatalog:CatalogFeed[]=rows.map(([name,url,category,language,description])=>({name,url,category,language,description}));
export const feedCategories=['全部',...new Set(feedCatalog.map(x=>x.category))];
export function searchCatalog(query:string,category='全部',language='全部'){const q=query.trim().toLowerCase();return feedCatalog.filter(x=>(category==='全部'||x.category===category)&&(language==='全部'||x.language===language)&&(!q||[x.name,x.description,x.url,x.category].join(' ').toLowerCase().includes(q)));}
