import {isLancetMetadata,lancetMetadataFeed,journalInfo} from './journal-feed';
export type Feed={id:string;name:string;url:string;selector?:string;category?:string;view?:string};
export type Article={id:string;feed:string;source:string;title:string;body:string;url:string;date:string;read?:boolean;star?:boolean;fullBody?:string;fullAt?:string;fullHtml?:string;bodyHtml?:string;type?:'article'|'video'|'audio'|'image';cover?:string;media?:string;bvid?:string};
function plain(html:string){const d=new DOMParser().parseFromString(html,'text/html');d.querySelectorAll('script,style,iframe').forEach(x=>x.remove());d.querySelectorAll('p,div,br,li,h1,h2,h3').forEach(x=>x.prepend('\n\n'));return(d.body.textContent||'').replace(/\n\s*\n/g,'\n\n').trim();}
function link(raw:string,base:string){if(!raw)return '';try{const u=new URL(raw,base);return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}}
function media(body:string,url:string,attachments:any[]=[],extra:any={}){const d=new DOMParser().parseFromString(body,'text/html');const cover=link(extra.cover||d.querySelector('img')?.getAttribute('src')||'',url);const file=attachments.find(x=>/^(audio|video)\//.test(x.mime_type||x.type||''));const source=file?.url||file?.href||'';const bvid=extra.bvid||url.match(/bilibili\.com\/video\/(BV[A-Za-z0-9]+)/)?.[1];const type=bvid?'video':file?(String(file.mime_type||file.type).startsWith('audio')?'audio':'video'):extra.type==='image'?'image':'article';return {type,cover:cover||undefined,media:link(source,url)||undefined,bvid};}
export function parseFeed(text:string,url:string):{feed:Feed;items:Article[]}{
 let name='',rows:any[]=[];
 if(text.trim().startsWith('{')){let d=JSON.parse(text);if(isLancetMetadata(new URL(url))&&Array.isArray(d.message?.items))d=lancetMetadataFeed(d.message.items,journalInfo(new URL(url))?.name);if(!Array.isArray(d.items))throw new Error('不是有效的 JSON Feed');name=d.title||new URL(url).hostname;rows=d.items.map((x:any)=>{const page=link(x.url||x.external_url||'',url),body=x.content_html||x.content_text||x.summary||'';return {title:x.title||'无标题',body:plain(body),bodyHtml:x.content_html||undefined,url:page,date:x.date_published||'',id:String(x.id||x.url||x.title),...media(body,page||url,x.attachments,x._yueliu)};});}
 else{const d=new DOMParser().parseFromString(text,'text/xml');if(d.querySelector('parsererror')||!d.querySelector('rss,feed,RDF'))throw new Error('未找到 RSS 或 Atom 内容');const get=(e:Element,n:string)=>Array.from(e.children).find(c=>c.localName===n);name=get(d.querySelector('channel')||d.documentElement,'title')?.textContent||new URL(url).hostname;rows=Array.from(d.querySelectorAll('item,entry')).map(e=>{const t=(n:string)=>get(e,n)?.textContent||'';const l=Array.from(e.children).find(c=>c.localName==='link'&&(!c.getAttribute('rel')||c.getAttribute('rel')==='alternate'));const page=link(l?.getAttribute('href')||l?.textContent||'',url),body=t('encoded')||t('content')||t('description')||t('summary');const attachments=Array.from(e.children).filter(c=>c.localName==='enclosure'||c.localName==='link'&&c.getAttribute('rel')==='enclosure').map(c=>({url:c.getAttribute('url')||c.getAttribute('href'),type:c.getAttribute('type')}));const thumb=e.getElementsByTagNameNS('*','thumbnail')[0]?.getAttribute('url');return {title:plain(t('title'))||'无标题',body:plain(body),bodyHtml:body,url:page,date:t('pubDate')||t('published')||t('updated'),id:t('guid')||t('id')||page||t('title'),...media(body,page||url,attachments,{cover:thumb})};});}
 const seen=new Set<string>();return {feed:{id:url,name,url},items:rows.filter(x=>{if(seen.has(x.id))return false;seen.add(x.id);return true;}).slice(0,100).map(x=>({...x,id:url+'::'+x.id,feed:url,source:name}))};
}
export function parseOPML(text:string):Feed[]{const d=new DOMParser().parseFromString(text,'text/xml');if(d.querySelector('parsererror')||!d.querySelector('opml'))throw new Error('请选择有效的 OPML 文件');const seen=new Set<string>();return Array.from(d.querySelectorAll('outline[xmlUrl]')).flatMap(e=>{const raw=e.getAttribute('xmlUrl')||'';let url='';try{const u=new URL(raw);if(!['https:','http:','rsshub:'].includes(u.protocol))return[];url=u.href;}catch{return[];}if(seen.has(url))return[];seen.add(url);const parent=e.parentElement;return[{id:url,url,name:e.getAttribute('title')||e.getAttribute('text')||url,category:parent?.tagName==='outline'?(parent.getAttribute('text')||parent.getAttribute('title')||'导入'):'导入'}];});}
export function exportOPML(feeds:Feed[]){const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const categories=[...new Set(feeds.filter(f=>!f.selector).map(f=>f.category||'未分组'))];return '<?xml version="1.0" encoding="UTF-8"?><opml version="2.0"><head><title>阅流订阅</title></head><body>'+categories.map(c=>'<outline text="'+esc(c)+'">'+feeds.filter(f=>!f.selector&&(f.category||'未分组')===c).map(f=>'<outline type="rss" text="'+esc(f.name)+'" xmlUrl="'+esc(f.url)+'"/>').join('')+'</outline>').join('')+'</body></opml>';}
export function feedRequest(url:string,origin:string){const u=new URL(url);const direct=u.origin===origin&&u.pathname==='/api/bilibili';return {direct,url:direct?u.pathname+u.search:'/api/feed?url='+encodeURIComponent(url)};}
