import {safeFetch,limitedText} from './remote';
export const journalMetadataCatalog=[{"kind": "lancet", "issn": "0140-6736", "name": "The Lancet", "url": "https://api.crossref.org/journals/0140-6736/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/0140-6736"}, {"kind": "lancet", "issn": "1470-2045", "name": "The Lancet Oncology", "url": "https://api.crossref.org/journals/1470-2045/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/1470-2045"}, {"kind": "lancet", "issn": "1473-3099", "name": "The Lancet Infectious Diseases", "url": "https://api.crossref.org/journals/1473-3099/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/1473-3099"}, {"kind": "lancet", "issn": "1474-4422", "name": "The Lancet Neurology", "url": "https://api.crossref.org/journals/1474-4422/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/1474-4422"}, {"kind": "lancet", "issn": "2213-2600", "name": "The Lancet Respiratory Medicine", "url": "https://api.crossref.org/journals/2213-2600/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/2213-2600"}, {"kind": "lancet", "issn": "2214-109X", "name": "The Lancet Global Health", "url": "https://api.crossref.org/journals/2214-109X/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/2214-109X"}, {"kind": "lancet", "issn": "2215-0366", "name": "The Lancet Psychiatry", "url": "https://api.crossref.org/journals/2215-0366/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/2215-0366"}, {"kind": "lancet", "issn": "2468-2667", "name": "The Lancet Public Health", "url": "https://api.crossref.org/journals/2468-2667/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/2468-2667"}, {"kind": "lancet", "issn": "2589-7500", "name": "The Lancet Digital Health", "url": "https://api.crossref.org/journals/2589-7500/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/2589-7500"}, {"kind": "lancet", "issn": "2665-9913", "name": "The Lancet Rheumatology", "url": "https://api.crossref.org/journals/2665-9913/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/2665-9913"}, {"kind": "lancet", "issn": "2352-4642", "name": "The Lancet Child & Adolescent Health", "url": "https://api.crossref.org/journals/2352-4642/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/2352-4642"}, {"kind": "lancet", "issn": "2589-5370", "name": "EClinicalMedicine", "url": "https://api.crossref.org/journals/2589-5370/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/2589-5370"}, {"kind": "lancet", "issn": "2352-3964", "name": "EBioMedicine", "url": "https://api.crossref.org/journals/2352-3964/works?sort=published&order=desc&rows=30", "source": "https://api.crossref.org/journals/2352-3964"}];
export function journalInfo(u:URL){return u.origin==='https://api.crossref.org'&&!u.username&&!u.password?journalMetadataCatalog.find(j=>u.pathname===`/journals/${j.issn}/works`):undefined;}
export function isLancetMetadata(u:URL){return Boolean(journalInfo(u));}
export function lancetMetadataFeed(items:any[],name='《柳叶刀》The Lancet'){
 return {version:'https://jsonfeed.org/version/1.1',title:name+' · Crossref 论文题录',home_page_url:'https://www.thelancet.com/',description:'Crossref 出版元数据，非期刊全文。',items:items.filter(x=>typeof x.DOI==='string'&&Array.isArray(x.title)&&x.title[0]).slice(0,30).map(x=>{
  const parts=(x.published||x['published-online']||x['published-print'])?.['date-parts']?.[0],date=parts&&parts.length>=1?`${parts[0]}-${String(parts[1]||1).padStart(2,'0')}-${String(parts[2]||1).padStart(2,'0')}T00:00:00Z`:undefined;
  const authors=(x.author||[]).map((a:any)=>[a.given,a.family].filter(Boolean).join(' ')).filter(Boolean).join('、');
  return {id:x.DOI,url:'https://doi.org/'+encodeURI(x.DOI),title:String(x.title[0]),content_text:`来源：Crossref 出版元数据（非全文）。\n\n${authors?'作者：'+authors+'\n\n':''}DOI：${x.DOI}\n\n本订阅提供论文题录。请通过 DOI 访问发布方页面；全文阅读范围取决于开放获取或订阅权限。`,...(date&&!isNaN(Date.parse(date))?{date_published:date}:{})};
 })};
}
export async function fetchLancetMetadata(u=new URL(journalMetadataCatalog[0].url)){
 const journal=journalInfo(u);if(!journal)throw new Error('不支持的期刊题录地址');
 const r=await safeFetch(journal.url,{signal:AbortSignal.timeout(20000),headers:{Accept:'application/json','User-Agent':'YueliuReader/1.2 (https://github.com/Tx13758627780/yueliu-reader)'}});
 if(!r.ok)throw new Error('Crossref 题录服务返回 HTTP '+r.status);
 const d=JSON.parse(await limitedText(r));if(!Array.isArray(d.message?.items))throw new Error('Crossref 没有返回有效的论文题录');return JSON.stringify(lancetMetadataFeed(d.message.items,journal.name));
}
