import {localAll,localGet,localPut} from './local-store';
import {notesFetch,type StoredNote} from './notes-client';
import {validateBoard} from './board';
import {apiFetch,isNative} from './api-client';
import type {Article} from './feed-reader';
export const MEDIA_CACHE='yueliu-media-v1';
export const imageKey=(raw:string)=>new URL('/api/image?url='+encodeURIComponent(raw),location.href).href;
export async function cachedImage(raw:string){if(isNative()){const blob=await localGet<Blob>('meta','image:'+raw);return blob?new Response(blob):null;}if(!('caches' in window))return null;return (await caches.open(MEDIA_CACHE)).match(imageKey(raw));}
export async function cacheImage(raw:string,r:Response){if(isNative())await localPut('meta','image:'+raw,await r.blob());else await (await caches.open(MEDIA_CACHE)).put(imageKey(raw),r);}
export async function saveArticleOffline(a:Article){const html=a.fullHtml||a.bodyHtml||'',doc=new DOMParser().parseFromString(html,'text/html');const urls=new Set<string>();for(const img of doc.querySelectorAll('img')){const raw=img.getAttribute('data-src')||img.getAttribute('data-original')||img.getAttribute('src');try{if(raw){const u=new URL(raw,a.url);if(/^https?:$/.test(u.protocol))urls.add(u.href);}}catch{}}if(a.cover)urls.add(a.cover);let ok=0,failed=0;for(const raw of urls){try{if(await cachedImage(raw)){ok++;continue;}const r=await apiFetch('/api/image?url='+encodeURIComponent(raw));if(!r.ok)throw new Error();await cacheImage(raw,r);ok++;}catch{failed++;}}const r=await notesFetch('/api/notes?article='+encodeURIComponent(a.url||a.id));for(const note of (await r.json()).notes)if(note.hasAudio){const audio=await notesFetch('/api/notes?audio='+note.id);if(!audio.ok)failed++;}return {ok,failed};}
export function downloadFile(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function blobData(blob:Blob){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});}
export async function exportBackup(){const rows=await localAll<StoredNote>('notes'),notes=[];for(const row of rows.filter(r=>!r.deleted))notes.push({note:row.note,audio:row.audio?await blobData(row.audio):undefined});const reader=await localGet('meta','reader-data'),outputs=await localGet('meta','ai-outputs');return new Blob([JSON.stringify({format:'yueliu-backup',version:1,created:new Date().toISOString(),reader,outputs,notes})],{type:'application/json'});}
export async function importBackup(file:File){if(file.size>150000000)throw new Error('备份请小于 150 MB');const data=JSON.parse(await file.text());if(data.format!=='yueliu-backup'||data.version!==1||!Array.isArray(data.notes)||data.notes.length>10000)throw new Error('不是有效的阅流备份');const prepared=[];for(const item of data.notes){const n=item.note;if(n?.kind==='board')validateBoard(n);else if(!n||!/^[a-f0-9-]{36}$/.test(n.id)||typeof n.article!=='string'||!Array.isArray(n.strokes)||typeof n.text!=='string'||typeof n.quote!=='string')throw new Error('备份包含无效笔记');let audio:Blob|undefined;if(item.audio){if(typeof item.audio!=='string'||!/^data:audio\/[\w.+-]+(?:;[^,]*)?;base64,/.test(item.audio))throw new Error('录音格式无效');const r=await fetch(item.audio);audio=await r.blob();if(audio.size>12000000)throw new Error('录音过大');}prepared.push({n,audio});}
 const validReader=(v:any)=>v&&Array.isArray(v.feeds)&&Array.isArray(v.articles)&&v.articles.every((a:any)=>typeof a.id==='string'&&typeof a.url==='string'&&typeof a.body==='string'&&typeof a.title==='string'&&typeof a.source==='string')&&v.feeds.every((f:any)=>typeof f.id==='string'&&typeof f.name==='string'&&typeof f.url==='string');if(data.reader&&!validReader(data.reader))throw new Error('备份中的文章格式无效');
 for(const {n,audio} of prepared){const old=await localGet<StoredNote>('notes',n.id);if(old&&!old.deleted&&(old.note.updated||0)>(n.updated||0))continue;await localPut('notes',n.id,{id:n.id,article:n.article,note:n,audio,dirty:true,revision:crypto.randomUUID()});}
 if(data.reader){const old=await localGet<any>('meta','reader-data')||{feeds:[],articles:[]};const merge=(a:any[],b:any[])=>[...new Map([...a,...b].map(x=>[x.id,x])).values()];await localPut('meta','reader-data',{feeds:merge(data.reader.feeds,old.feeds),articles:merge(data.reader.articles,old.articles)});}if(data.outputs){const old=await localGet<any>('meta','ai-outputs')||{};await localPut('meta','ai-outputs',{outputs:{...data.outputs.outputs,...old.outputs},answer:{...data.outputs.answer,...old.answer}});}return prepared.length;
}
