import React from 'react';
import {createRoot} from 'react-dom/client';
import {Capacitor} from '@capacitor/core';
import {androidBackStack} from '../../lib/back-navigation';
import Home from '../../app/page';
import '../../app/globals.css';
(window as any).__YUELIU_NATIVE__=!!(window as any).yueliuDesktop||Capacitor.isNativePlatform();
(window as any).__YUELIU_ANDROID__=Capacitor.getPlatform()==='android';
(window as any).__yueliuBack=()=>androidBackStack.back();
createRoot(document.getElementById('root')!).render(<Home/>);
